CodeSquad-Algorithm/Algorithm

- src/산토리/연결 요소의 개수.py
안녕하세요. 산토리입니다~
#1 문제 풀어서 PR 올립니다~
문제 난이도에 비해 어려웠습니다!!!
그래프를 잘 이해하고 있어야 풀 수 있는 문제였던 것 같습니다.
- 섬을 찾으려면, 임의의 노드에서 시작해 그 노드에서 갈 수 있는 모든 노드를 조사하면 된다.
- BFS를 활용하여 한 노드에 연결된 모든 노드를 방문처리한다.
- 방문하지 않은 노드가 있는지 다시 탐색한다. 
- 방문하지 않은 노드가 나올 때마다 다른 연결요소가 존재한다는 것이므로 답에 1을 더한다.
> [산토리] #1 문제풀이 업로드

- src/아더/BOJ_11724_연결요소의개수.java
- src/아더/BOJ_2512_예산.java
안녕하세요 아더입니다!
일단 문제를 풀기위해 그래프에 대해 이해를 잘 해야 풀 수 있는 문제를 고른 것 같아 죄송합니다..... 🙇‍♂️
1. 먼저 2차원배열에 무방향 그래프의 각 요소를 저장합니다. 연결되어 있다면 양방향 모두 1을 셋팅합니다.
2. 다음은 방문하지 않은 정점을 대상으로 dfs를 수행합니다.
3. dfs를 시작할 때 방문점에 방문체크를 해주고 해당 점과 연결되어 있고 방문하지 않은 점을 대상으로 다시 dfs를 수행합니다.
4. 결국 한 점에 대해 dfs를 수행하면 연결되어 있는 정점은 모두 방문처리가 되며 메인으로 dfs를 수행하던 함수에서 dfs가 끝날때마다 카운트를 더해주면 연결요소의 갯수를 구할 수 있습니다.
1. 처음에는 union과 find 방법으로 접근했습니다. 
2. 이렇게 풀이하니 90%대에서 "틀렸습니다"가 나왔습니다.
3. 그 이유는 연결요소라는 것이 하나의 정점만 존재해도 연결요소로 카운트되는 것을 놓쳐서 그렇습니다.
> [Ader] BOJ(11724) : 연결요소의 개수 #1 - 풀이제출

- src/땃쥐/BOJ_11724_1.java
- src/땃쥐/BOJ_11724_2.java
- src/땃쥐/Sample.java
늦어서 죄송합니다. 두가지 풀이를 알아봤습니다. DFS, BFS 두가지 개념인데요.
---
DFS는 시작점을 기준으로 하여, 인접한 노드가 여럿 있을 때 일반적으로 그들중 한 노드를 기준으로 가장 깊게 들어가서 탐색한 뒤 그 다음 깊이의 노드를 탐색하는 방식으로, 일반적으로 Stack 형태의 자료구조, 재귀 함수를 사용하는 것으로 확인했습니다.
BFS는 시작점을 기준으로 인접한 노드를 한번 탐색하고 그들 각각에 대하여 다음 노드를 탐색하는 구조로 주로 큐 형태의 자료구조를 사용하는 것으로 확인했습니다.
---
> [땃쥐] 20220302 BOJ_11724 풀이 제출

- src/제이/1주차/BOJ_11724.java
- src/제이/1주차/BOJ_2512.java
https://www.acmicpc.net/problem/11724
일단 문제를 이해하는것 부터 난항이었습니다😭
`연결 요소`라는게 뭔지 몰라서, 이게 뭔지 이해하는데 한 세월이 걸렸습니다.
그리고 이때까지 좌표평면에서 BFS는 넓이 구하기, DFS는 경로 탐색의 유형만 풀어봤었습니다.
그래서 문제에 있던 예시의 `1 2`, `2 5` 를 좌표평면의 x, y 좌표로 생각했습니다.
(1,2)---(2,5) 이런식으로 점과 점이 연결되어 선을 이룬다고 이해했었습니다.
그런데 이런 방식으로 하면, '모든 점들이 다 연결되는데, 어떻게 연결 요소가 생기는 거지?' 하면서 몇 시간을 보냈습니다 ㅎㅎ;
어떻게하면 이 문제에도 BFS나 DFS를 적용할 수 있을지 감이 잘 안잡혔습니다.
이게 어떻게 BFS/DFS로 되는건지 몇시간동안 고민하다 안되겠다 싶어서 결국 해답을 찾아봤습니다.
결국 BFS로 풀었는데요.
그래도 이 문제에 대해 조금 이해도 했고 정답도 맞췃지만, 왜 이렇게 풀이해야하는지 아직 100% 이해되진 않네요.
그래프에 대해 이해가 부족한 것 같아서, 그래프에 대해 더 공부해야할 것 같습니다.
----
어제가 지나기 전가지 제출했어야했는데.. 늦어진점 죄송합니다😢
> [제이] 연결 요소의 개수 풀이 추가

- src/땃쥐/BOJ_2512_1.java
- src/땃쥐/BOJ_2512_2.java
- src/땃쥐/Sample.java
안녕하세요. 알고리즘 정말 어렵네요 ㅜㅜ
개인적 풀이를 일단 하나 올립니다.
---
```java
int[] budgets = new int[N]; // 예산들
for(int i=0; i<N; i++) {
budgets[i] = Integer.parseInt(st.nextToken());
}
Arrays.sort(budgets); // 오름차순 정렬
```
- 값들을 입력받아서 배열로 저장해둔 뒤, 정렬한다.
- 정렬을 했으므로, 제일 끝 값은 최댓값이다.
```java
int M = Integer.parseInt(br.readLine()); // 예산 총액
while (sum(budgets) > M) { // 예산총액보다 합계가 클 때
budgets[N-1] --; // 최댓값을 1 줄인다.
for (int i=0; i<N; i++) {
if (budgets[i] > budgets[N-1]) { // 각각의 값이 최댓값보다 클 경우
budgets[i] --;
}
}
}
System.out.print(budgets[N-1]);
```
- 예산 총액을 입력받고, 예산 총액과 예산 배열의 합계를 비교하여, 합계가 더 클 경우
- 최대 예산값을 1 감소시키고, 배열의 각 요소들을 탐색하여 최댓값보다 클 경우 1씩 삭감한다.
- 이를 반복하여 예산총액이 합계보다 작거나 같게 되면, 반복을 탈출한다.
- 최종적으로 예산의 최댓값(예산 배열의 끝값)을 출력한다.
---
이진탐색의 매개변수 탐색
- https://annajeong.github.io/algorithm/parametric/ 참고
---
- 음... …
> [땃쥐] 220303 BOJ_2512

- src/밀러/BOJ_11724.py
- src/밀러/BOJ_2512.py
안녕하세요, BOJ_2512 풀이를 갖고온 Miller 입니다. 😀
이 문제.. 처음에 생각했던 방법으로 해결하지 못했습니다.
그리고 이분탐색과 파라메트릭 서치에 대해서 공부하고 온 뒤 아래와 같이 해결했습니다.
```python
mid: int = 0
while left <= right:
mid = (left + right) // 2
total: int = 0
count: int = 0
for budget in budgets:
if budget < mid:
total += budget
else:
count += 1
total += mid
if M - count < total <= M:
return mid
elif total > M:
right = mid - 1
else:
left = mid + 1
```
먼저 문제 상 최소 예산 값과 최대 예산 값을 `left`, `right` 로 설정한 뒤,
이분 탐색을 진행하면서 최대 상한값을 찾습니다.
아직 이분 탐색이 익숙하지 않아서, if 문에 return 조건, else if/else 문에서 left, right 값을 할당합니다.
그리고 입력된 예산을 순회하면서 현재 mid 값이 상한값에 해당하는지 검사합니다.
> [Miller] #2 BOJ_2512 풀이 제출

- src/제이/1주차/BOJ_11724.java
- src/제이/week1/BOJ_11724.java
- src/제이/week1/BOJ_2512.java
https://www.acmicpc.net/problem/2512
제가 모르는게 넘 많다고 느꼈습니다 ㅠㅠ
누적합, 이분탐색, 매개변수 탐색... 
이분탐색은 뭔지는 알지만 이 문제에 어떻게 적용해야할지 딱 떠오르지 않더라구요.
문제를 더 많이 풀어봐야겠습니다..
저번 문제는 결국 정답을 봐버린게 너무 아쉬워서 계속 답을 안보고 풀려고 했는데
그 때문에 이번 문제는 너무 오래 잡고있었던것 같네요ㅠㅠ
`누적합` 이라는 키워드를 짱민이 던져주셔서, 이에 대해서 조금 공부한 다음 누적합으로 이 문제를 먼저 접근했습니다.
예산의 개수만큼 누적된 합을 구해놓고 시작했는데요.
맨 뒤(총합) 부터 한칸씩 앞으로 오면서 남은 개수랑 더 필요한 예산을 나누는 방식으로 하면 되겠다고 생각했습니다.
그런데 생각처럼 되지 않았고, 누적합을 이용한 풀이를 이렇게 하는지 잘 모르겠더라구요..
누적합으로 도저히 안되겠다 싶어서, 그 다음에 `아더`가 던져주신 키워드 매개변수 탐색에 대해 알아봤습니다.
https://kosaf04pyh.tistory.com/95
이 블로그 글이 정말 도움이 많이 됐습니다.
여기서 설명하면서 예시로 나온 문제가 이번 예산 문제랑 완전 동일한 유형의 문제여서, 
이 글에서 제시한 풀이 방법을 예산에 그대로 적용하니 문제가 금방 풀렸습니다.
----
아직 알고리즘과 문제가 딱딱 매칭이 안되는것 같네요..
어떤 유형의 알고리즘이 있는지 알고, 그 원리를 다 알고있어야 여러 문제들을 풀때 OO 알고리즘을 써봐야겠다!
생각할 수 있을 것 같은데, 아직 제가 모르는게 넘 많은 것 같습니다.
혹시 다양한 알고리즘 …
> [제이] BOJ(2512) : 예산 풀이 추가 

- src/제이/1주차/BOJ_11724.java
- src/제이/week1/BOJ_11660.java
- src/제이/week1/BOJ_11724.java
- src/제이/week1/BOJ_2512.java
https://www.acmicpc.net/problem/11660
처음에는 범위를 브루트포스로 해봤더니, 시간 초과가 나왔습니다.
그래서 계속 고민하다가 지난 문제에서 `짱민`이 언급했었던 누적합이 생각나서, 
누적합으로 풀어보기로 하였습니다.
행렬 전체 범위에 대해 누적합을 구하고, 해당되지 않는 범위를 제거하는 방식을 시도했습니다.
그래도 시간 초과가 나서, 멘붕에 빠졌습니다...
누적합이 아닌가 생각이 들었는데, 아무리 생각해도 시간 복잡도를 줄이려면 무조건 누적합을 이용해야한다고 생각했습니다.
아무리 생각해도 안풀려서, 덮어두고 다른일을 하다가 갑자기 문득 세로로 누적합을 구하면 어떨까 생각했습니다.
그래서 세로로 누적합을 구하고, 해당되지 않는 범위를 구하는 방식으로 구현하여 성공할 수 있었습니다.
> [제이] BOJ(11660) : 구간 합 구하기 5 - 문제풀이

- src/짱민/11660_1.py
전에 풀었던 문제인데 문제를 잘못 읽어서 헤맸습니다
python3로는 시간초과가 나서 pypy로 제출했습니다.
구간합을 이용했습니다....
> [zzangmin] 구간합구하기5

- src/밀러/BOJ_11660.py
- src/밀러/BOJ_11724.py
안녕하세요, BOJ_11660 풀이를 갖고온 밀러입니다. 😀
이 문제는 행의 수 N이 최대 1024, 구해야하는 합의 횟수 M이 최대 100,000 입니다
평소에 시간복잡도를 생각하지 않고 푸는 습관이 있어,
처음에는 주어진 범위 내의 모든 수를 더하는 방법으로 풀이했습니다.
그러면 연산횟수가 1024 * 1024 * 100,000 = 104,857,600,000 으로 
제한 시간인 1초동안 최대 2000만~1억번의 연산이 가능한 파이썬에서 TLE 가 발생합니다.
하지만 각 행마다 구간합을 구해놓고 계산하면,
1024 * 100,000 = 102,400,000 으로 제한 시간동안 풀릴수도? 있습니다.
만약 안되면 각 행이 아닌 각 2차원 영역마다 구간합을 계산해야했을 겁니다.
그런데 일단 행마다 구간합을 구하는 방법으로 제한 시간을 통과했기 때문에,
해당 방법으로 해답을 제출합니다!
> [Miller] #3 BOJ_11660 풀이 제출

- src/땃쥐/BOJ_11660_1.java
- src/땃쥐/BOJ_11660_2.java
- src/땃쥐/Sample.java
이번 문제도 처음에 무식하게 풀어서 시간초과가 났었는데요.
DP라는 알고리즘에 대해 한번 살짝 읽어보고, 좀 더 고민하다가 누적합이라는 개념을 확인하고 답안을 조금씩 살펴보면서 풀었습니다.
---
```java
for (int i=0; i<N; i++) {
for (int j=0; j<N; j++) {
numbers [i][j] = readInt();
}
}
StringBuilder sb = new StringBuilder();
for (int i=0; i<M; i++) {
int t1 = readInt()-1;
int u1 = readInt()-1;
int t2 = readInt()-1;
int u2 = readInt()-1;
int sum = 0;
for (int j=t1; j<=t2; j++) {
for (int k=u1; k<=u2; k++) {
sum += numbers[j][k];
}
}
sb.append(sum).append('\n');
}
System.out.print(sb);
}
```
- 각 행/열별 값을 전부 저장해둠
- 필요한 영역만큼 반복 돌려서 전부 합산
- 결과 : 실패 (행, 열 이 기하급수적으로 많아질 경우 그만큼을 전부 더해야하므로 어마어마한 시간이 걸린다.)
---
```java
int[][] dp = new int[N+1][N+1];
// 누적합
for (int i=1; i<=N; i++) {
for (int j=1; j<=N; j++) {
dp[i][j] = dp[i-1][j] + dp[i][j-1] - dp[i-1][j-1] + readInt();
}
}
```
- 각 …
> [땃쥐] BOJ(11660) : 구간 합 구하기 5 - 문제풀이

- src/땃쥐/BOJ_15787.java
탄다 : true
비어있다 : false
- 1명령 : 열차의 특정 칸의 값을 true로 변경... 리스트인가?
- 2명령 : 열차의 특정 칸의 값을 false로 변경하는 상황이군...!
- 3명령 : 오른쪽으로 밀어버린다... Queue인가?
- 4명령 : 왼쪽으로 밀어버린다... Deque 인가?
- 같은 자리 배치구조이면 은하수를 건널 수 없다. -- 중복을 허용하지 않는다!
---
탄다, 비어있다는 것은 처음 생각한대로 이분적인 문제인 것 같아서 그대로 사용하기로 했습니다.
근데 제가 아는 내에서 특정 인덱스의 값을 변경할 수 있으면서 Deque의 성격을 가진 자료구조는 없었습니다.
자바에서 LinkedList는 이들을 구현한 것이라서 이렇게 풀수는 있을 것 같긴 했는데 이는 자바의 특정 라이브러리에 종속된 풀이라서 이렇게 풀면 안 될겠다는 생각이 들었습니다.
---
- 비트마스킹... 그러고보면 CS때 다른 고수분들이 비트연산자를 이용해 정수값을 조작하는 것이 생각났습니다.
- 결국은 true, false라는 이분적인 상황을 다루는 것이라는 점에서... 딱 이 키워드 읽고 무릎을 딱 쳤습니다. 아아...!
- 근데 제가 비트를 다루는 기법에는 익숙하지 않아서 일단 자바의 정석, 인터넷을 검색하면서 비트연산자에 대해 찾아보았습니다.
---
- `&` : And(둘다 1이면 1)
- `|` : or (적어도 하나가 1이면 1)
- `^` : XOR (비트가 다르면 1)
- `~` : Not (모든 비트 뒤집기)
- `<<` : 비트들을 왼쪽으로 밀기
- `>>` : 비트들을 오른쪽으로 밀기 (맨앞 …
> [땃쥐] BOJ(15787) : 기차가 어둠을 헤치고 은하수를 - 문제풀이

- src/밀러/BOJ_15787.py
역시 짱민은 출제하는 문제도 꿀잼이군요 😀😀
명령을 처리할 때는 deque 자료구조 문제가 아닐까 생각했는데,
겹치지 않는 기차의 개수를 세는 것을 보고 비트 연산으로 풀어야겠다고 생각했습니다.
m 개의 명령을 처리하는데 걸리는 시간 복잡도 O(m)
n 개의 기차가 겹치는지 확인하는데 걸리는 시간 복잡도 O(n)
-> O(m) 또는 O(n)
문제 접근까지는 빨랐는데 비트 연산을 잘 몰라서 헤맸습니다.
아래 참고 링크를 보고서 어떻게 연산해야할지 알 수 있었습니다.
https://justkode.kr/algorithm/bitmash
> [Miller] BOJ(15787): 기차가 어둠을 헤치고 은하수를 - 문제풀이

- src/아더/BOJ_2003_수들의합2.java
안녕하세요 아더입니다~!
투 포인터를 오랜만에 풀어봐서 개념 다시 기억해내는데 좀 걸렸네요 ㅋㅋㅋ
왼쪽 포인터와 오른쪽 포인터가 각각 움직이지만 최대 O(N)번씩 움직이므로 최종적인 시간복잡도는 O(N)입니다!
1. 투 포인터 개념을 타겟으로 잡고 출제한 문제다보니 투 포인터를 써야겠다고 마음먹었습니다.
2. 몰랐다고 가정을 했을 때도 완전탐색을 했을 시 O(N^2)이 될텐데 시간제한이 0.5초라 완전탐색을 시도하진 않았을 것 같아요.
3. 왼쪽 포인터와 오른쪽 포인터를 독립적으로 움직여 그 구간의 합이 M이 될 때만 answer의 값을 1씩 증가시켰습니다!
1. 오늘은 삽질이 없네요^^
> [Ader] BOJ(2003): 수들의 합 2 - 문제풀이

- src/땃쥐/BOJ_2003.java
안녕하세요. 수들의합 2 문제풀이 풀리퀘 올려봅니다.
---
포인터 두개를 기준으로 for문을 돌지만, 한 for문 내에서 조건에 따라 값이 증가하는 식이고 전부 돌지는 않기에 시간 복잡도는  O(N)입니다.
---
```java
int[] sums = new int[N+1];
for (int i=1; i<=N; i++) {
sums[i] = sums[i-1] + readInt();
}
```
1. 구간에서의 수의 합을 구하는 과정인데 이 부분은 전에 배웠던, 누적합을 활용했습니다.
```java
for (int point1 = 1, point2 = 1; point1 <= N && point2 <= N; ) {
int sum = sums[point2] - sums[point1 - 1];
if (sum >= M) {
point1++;
point2 = point1;
if (sum == M) {
count++;
}
} else {
point2++;
}
}
```
2. 조건에 맞는 경우의 수를 구할 때는 포인터 두개를 도입하여 루프 한번으로 조건에 따라 포인터를 움직이는 식으로 처리했습니다.  
**3. 결과 : 140ms**
---
```java
int count = 0;
for (int point1=1; point1<=N; point1++) {
for (int point2=1; point2<=N; point2++) {
if (sums[point2] - sums[point1 - 1] == M) {
count ++;
}
}
}
```
- 처음에는 2중 for문으로 변수를 싹다 돌렸었는데, 생각해보면 반복이 쓸데 …
> [땃쥐] BOJ(2003): 수들의 합 2 - 문제풀이

- src/제이/week2/BOJ_1463.java
너무 어려웠습니다.... ㅠㅠㅠㅠㅠㅠㅠ
DP를 활용해서 풀었기 때문에, n 부터 1 까지 숫자는 한번만 계산됩니다.
그래서 `O(n)` 의 시간복잡도를 가집니다.
이 문제는 도저히 안되겠어서, 해답을 보고 풀었습니다...
처음 풀어보는 유형의 문제는 6시간 이상 고민해도 안풀리면, 그냥 답을 보고 풉니다..
대신에 풀이를 꼼꼼히 분석해서 다음에는 이런 유형의 문제를 풀 수 있도록 공부하려고 합니다.
처음에는 엣지 케이스만 잘 잡아주면 풀릴 것 같다고 생각해서, 계속 경우의 수를 추가해봤습니다.
그런데 끝이 없어서, 이거는 알고리즘으로 풀어야되는것 같다는 생각이 들었고,
결국 백준 힌트를 얻고자 `질문 검색` 에서 질문글들의 제목만 읽었고, 여기서 DP 라는 힌트를 얻었습니다.
DP 라는 힌트를 얻고도, 이 문제에 DP를 어떻게 적용시켜야하는지 도저히 감이 안왔습니다.
- 1 부터 n 까지 올라야 하나?
- 기존 엣지케이스 유지하면서 DP를 이용해야 하나?
- 재귀호출 함수에 count 를 파라미터로 주면서 1 이 되면 반환하는 형식?
여러 생각이 들었지만, 코드로 옮겨지지가 않았습니다..
한참 머리를 싸매다가, 너무 시간 가성비(?)가 안나오는것 같아서 결국 해답을 찾아보고 말았습니다..
> [Jay] BOJ(1463): 1로 만들기

- src/산토리/1로 만들기.py
안녕하세요. 산토리입니다.
토요일 문제 풀이 업로드합니다~
사실 예전에 풀었던 문제라 어렴풋이 기억났는데 실수로 알고리즘 분류를 봐버려서 dp로 접근하긴 했습니다.
N에서부터 1로 내려가는 건 dp로 접근하기 어려워보여서 역으로 1부터 계단 올라가는 문제처럼 dp로 접근해봤습니다.
가령 n으로 접근할 때, 가는 경우의 수는 n-1으로부터 1칸 이동, (2의 배수라면) n/2으로부터 2배 이동, (3의 배수라면) n/3으로부터 3배 이동이 있습니다. 각 경우의 수 중에 최솟값에 1을 더하면서 dp[n]을 갱신하면 매 숫자에 접근하는 최소 경우의 수가 dp 배열에 저장됩니다.
그렇기 때문에 1부터 N까지 진행하면서 min(n-1에 도달하는 최솟값, n/2에 도달하는 최솟값, n/3에 도달하는 최솟값)+1 으로 dp[n]을 갱신해가면 dp[N]이 정답이 됩니다. 
오늘은 오전에 코테를 치르고 와서인지 감각이 살아있어 삽질을 많이 안했네요!
1부터 N까지 순회하므로 O(N), N이 최대 10^6=1,000,000이므로 시간제한 문제 없음.
> [산토리] BOJ(1463): 1로 만들기 - 문제풀이 업로드

- src/밀러/PROGRAMMERS_42898.py
안녕하세요 프로그래머스 42898 등굣길 문제풀이를 들고온 Miller 입니다 🏄‍♂️
아래의 점화식을 바탕으로 문제를 풀이했습니다.
```text
dp[row][col] = dp[row - 1][col] + dp[row][col - 1]
```
`puddle` 이 있는 지점은 따로 2차원 배열로 관리하고,
`row` 와 `col` 을 2중 `for` 문 순회하면서 `puddle` 이 있는 지점은 스킵하고 계산하도록 했습니다.
문제에서 `m` 과 `n` 을 거꾸로 주어서 삽질 했습니다..
`row 와 `col` 을 2중 `for` 문 순회하니까 O(mn) 이 되겠네요!
> [Miller] 프로그래머스 (42898) : 등굣길 - 문제풀이

- src/제이/week3/Programmers_42898.java
쉬울줄 알았는데 삽질 많이했습니다..ㅎㅎ
---
이중 반복문으로 m*n 만큼 반복하기때문에, O(mn) 입니다.
범위가 1 <= m,n <= 100 이기 때문에, 최악의 경우에도 10,000회 실행됩니다.
그래서 시간 복잡도에 불리한 이중 반복문으로 풀이해도, 효율성 테스트를 통과할 수 있었습니다.
(선생님들이 puddles 반대로 되어있다고 알려주셔서 이 부분은 삽질을 안했습니다 ㅎㅎ 감사합니다🙏)
처음에는 BFS 로 풀었는데, 엣지케이스를 생각못해서 `정확도`에서 일부를 계속 틀렸습니다.
그래서 도착 못하는 엣지케이스를 고려해서 풀고나니, 이제는 `효율성`이 문제였습니다.
이중반복문 시간복잡도가 크지 않은 것 같아, 그냥 이중 반복문으로 변경하니 효율성도 통과했습니다!
방향이 정해져있는 경로의 개수를 구하는 문제인데, 해당 문제는 `좌상단`->`우하단` 방향입니다.
그래서 특정 좌표의 `위` + `왼쪽` 경우의 수의 합이 특정 좌표로 이동할 수 있는 경우의 수 입니다.
> [Jay] 프로그래머스 (42898) : 등굣길 - 문제풀이

- src/땃쥐/BOJ_1780.java
처음 이 문제를 풀 때는 배경지식이 없어서 일단 검색부터 했습니다.
저는 알고리즘 입문 단계에서, 뭐가 뭔지모르는 상태에서 엄청 많은 시간 생각해서 푸는 것은 사칙연산으로 미적분 문제를 푸는 것이라고 생각하고 있습니다. 저는 믿음과 신뢰의 힌트를 신봉합니다. 언젠가 의존성을 줄여야겠지만요 ㅜ
일단 하단의 힌트를 보면 이 문제의 알고리즘은 '분할정복'이라고 되어있는데요. 분할 정복이란 알고리즘은 전체 문제가 여러 작은 문제들로 구성되어 있는 상황이고 이 문제들을 작은 요소들로 쪼개서 하나하나 처리한뒤 통합해서 처리하는 알고리즘이라는군요.
---
우선 한 줄의 길이는 N은 3^k 꼴입니다. 3으로 나누고 3으로 나누고... 하면서 제일 최소한으로 줄이면 1개 단위가 됩니다.
주어진 문제에서 가장 이상적인 상황은 한번 쭉 숫자들을 다 탐색해봤는데 모두 숫자가 같은 경우인데요. 이 경우에는 일단 한번 싹 탐색하고 더 깊이 따질 것 없이 바로 카운팅해버리고 끝내면 됩니다.
하지만 그렇지 않은 경우가 있기 마련인데 이 경우에는 9개로 쪼개서, 각각에 대해 쪼개는 수밖에 없습니다.
---
```java
private static int[] counter = new int[3]; // -1, 0, 1짜리로만 채워진 종이 갯수
private static int[][] numbers; // 숫자들
int N = readInt(); // 한 줄당 숫자 갯수
numbers = new int[N][N]; // 숫자들
for …
```
> [땃쥐] BOJ (1780) : 종이의 개수 - 문제 풀이

- src/아더/BOJ_2579_계단오르기.java
기존에 풀어봤던 문제라서 풀이방법은 금방 생각났습니다!
다만 실제 구현하는 부분에서 조금 헤맸네요 ㅠㅠ
DP로 구현했기에 O(N)으로 생각되네요!
1. i번째의 계단에 오를 수 있는 방법은 `i-2 계단`에서 현재 계단을 밟는 것, `i-1 계단`에서 현재 계단을 밟는 것으로 나누어 생각합니다.
2. 각 계단을 밟지않고 현재 계단을 밟는 방법도 있으니 이를 고려해주기 위해 각 DP배열에 추가로 1차원을 더 구성해 계단 밟음 여부를 추가로 고려해주었습니다.
1. `i-1 계단`과 `i-2 계단`에서 `i 계단`에 접근한다는 것은 알지만 밟지않는다는 판단을 떠올리는데 좀 걸렸네요.
> [Ader] BOJ(2579): 계단 오르기 - 문제풀이

- src/제이/week4/BOJ_14888.java
재귀에다가 사칙연산(4개)의 경우의 수만 반복되니 시간복잡도를 계산하기가 어렵네요..
만약 숫자가 n 개라면,  O( (n-1)! )  보다 적은 시간이 걸리지 않을까... 싶은데 확신은 없네요.
처음에 재귀호출을 통해 풀면 되겠다 싶었습니다.
머리를 쥐어짜봐도, 이건 다 확인해야만 알 수 있겠다는 생각이 들었습니다.
```
void recursiveCalc() {
if 마지막수게산
max, min 에 대입
return;
if 더하기?
recursiveCalc(더하기)
if 빼기?
recursiveCalc(빼기)
if 곱하기?
recursiveCalc(곱하기)
if 나누기?
recursiveCalc(나누기)
}
```
위 처럼 처음에는 접근했는데, 연산자의 순서가 정해져버려서 정확한 값이 출력되지 않았습니다.
그래서 아무리 머리를 싸매도 답이 보이지 않아서, 결국 정답을 보고야 말았습니다...ㅠㅠ
재귀를 활용하려는 생각까지는 괜찮았으나, 그 후 연산자 순서를 동적으로 바꿔가며 계산하는 로직을 생각하지 목하여
위의 예시 코드와 같은 형식에서 사로잡혀서 벗어나지 못했습니다.
> [Jay] BOJ (14888) : 연산자 끼워넣기- 문제 풀이

- src/제이/week4/Programmers_81302.java
5 x 5 크기의 방 5개를 확인하면 좌표의 개수는 5 x 5 x 5 = 125 입니다.
그리고 `상하좌우`, `맨하탄 거리 상하좌우`, `4방향 대각선`  을 확인하기 때문에, 각 좌표마다 12 번 확인합니다.
그래서 최악의 경우 125 x 12 = 1500 번 확인하게 됩니다.
문제에서 방의 크기와 개수를 **고정된 크기**로 제공해주었기 때문에 상수로 계산해봤는데요.
이를 빅오 표현식으로 바꿔보면(방 개수 N, 방 가로 X, 방 세로 Y)
`O(12 * N * X * Y )` → `O(NXY)` 로 표한할 수 있을 것 같습니다.
처음에는 `BFS` 로 풀어야하나 잠깐 생각했지만, 확인할 위치들이 정형화되어있어서 하나 하나 확인하는 방식도 되겠다고 생각했습니다.
그래서 정말 단순하게 `상하좌우`, `맨하탄 거리 상하좌우`, `4방향 대각선`  을 확인하여 문제를 풀이했습니다.
삽질 과정은 없었습니다.
> [Jay] Programmers (81302) : 거리두기 확인하기- 문제 풀이

- src/산토리/거리두기 확인하기.py
- src/산토리/연산자 끼워넣기.py
안녕하세요. 산토리입니다.
목요일 문제 풀이 업로드합니다~
그냥 단순 구현문제인 것 같아서 무식하게 풀었습니다.
1. board를 모두 탐색하면서 응시자를 발견하면 응시자의 상하좌우를 검색합니다.
2. 상하좌우에 응시자가 존재하면 거리두기를 지키지 않은 것이므로 0을 추가하고 끝냅니다.
3. 응시자는 없지만 상하좌우에 빈 좌석이 있는 경우 빈 좌석으로부터 상하좌우를 조사합니다.
4. 빈 좌석 상하좌우에 본인을 제외한 다른 응시자가 있는 경우 역시 거리두기를 지키지 않은 것이므로 0을 추가하고 끝냅니다.
5. 모든 응시자에 대해 위 과정을 통과하며 1을 추가합니다.    
처음에 빈칸일때만 검색해서 상하좌우에 응시자가 있는 경우를 놓칠 뻔 했네요
인덴트가 매우 복잡해보이지만 ... 결국은 O(n^2)인 것 같네요. (n: 2차원 배열의 크기)
> [산토리] Programmers (81302): 거리두기 확인하기- 문제 풀이

- src/짱민/14888.py
- src/짱민/거리두기 확인하기.py
하위~~
구현문제인 것 같아서 그냥 생각없이 풀었습니다..
맨해튼 거리를 알려주길래 함수를 만들었지만 낚시였습니다
처음엔 dfs로 탐색하는 것으로 생각했는데, bfs를 해야 탐색 조건에 부합하지 않으면 도중에 중단하는 것이 용이해서  bfs를 선택했습니다
풀이 흐름 :
* places는 3차원 배열이므로 하나씩 2차원 배열을 순회하며 풀이
* P_list() 메서드로 place 안의 "P" 위치를 peoples 리스트에 저장
* peoples에 있는 좌표를 순회하며 bfs로 탐색
* bfs안에서는 dist 변수를 따로 둬서 현재 탐색 중인 dist가 2 미만일때만 큐에 삽입
* 그럼 탐색중에 "P"를 만났다는 것은 거리두기가 지켜지지 않은 것이므로 False 반환
* False가 반환되면 ans에 0을 넣고 break로 빠져나옴
* False가 반환된 적 없이 모든 순회가 끝났다면 ans에 1을 넣음
* 최적화 될 여지가 많은 로직입니다
* 코드는 보지 말아주세요 진짜 개판입니다
처음에 "X" 조건을 보지 못하고 "X"를 만났을때도 큐에 집어넣어서 탐색을 예상치 못한 방향으로 진행하는 바람에 디버깅하는데 시간을 조금 뺐습니다.
people 리스트를 만들때 N번 순회,
P가 있는 모든 위치를 순회하므로 또 한번 O(N) 입니다.
최악의 경우는 5*5 배열이 모두 P인 경우인데, O(N*3) 정도일 것 같습니다
> [zzang] Programmers (81302): 거리두기 확인하기- 문제 풀이 #72

- src/땃쥐/Programmers_81302.java
- 안녕하세요... 요즘 다른 공부를 이것저것 손대느라 알고리즘을 할 시간을 내기 힘든게 참 곤란해지고 있습니다.
- 매번 할 때마다 답을 봐야 이해되는 상황에서 솔직히 자신감을 잃고 있습니다...
---
- 우선 방의 갯수는 5개
- 2중  for문으로 5*5로 25개 좌표를 탐색
- 거기에 더해서 각 사람 기준으로 최악의 경우 12개 범위를 탐색해야합니다. 물론 모든 좌표에 사람이 있을 경우 그냥 매 순간 사람 옆자리에 사람이 있는게 판단되서 그 순간 모든 좌표마다 위험성이 판단되니 금방 BFS를 탈출하겠지만요.
- 시간복잡도는 대략 O(125*...)가 될 것 같습니다.
- 답을 확인했습니다...
```java
private static final char PERSON = 'P';
private static final char EMPTY = 'O';
public int[] solution(String[][] places) {
int[] answer = new int[places.length];
for (int numberOfPlace = 0; numberOfPlace < places.length; numberOfPlace++) { // 각 대기실마다 안전성 여부를 판단한다.
answer[numberOfPlace] =
isSafePlace(places[numberOfPlace])
? 1
: 0;
}
return answer;
}
```
- static 상수 : PERSON, EMPTY를 저장해둡니다.
- 각각의 대기실마다, isSafePlace 메서드를 통해 안전성 여부를 판단하고, true이면 1, …
> [땃쥐] Programmers (81302): 거리두기 확인하기 - 문제 풀이

- src/아더/BOJ_16918_봄버맨.java
문제가 마치 짱민처럼 꿀잼이네요 ㅋㅋㅋ 재밌게 풀었습니다!
구현 문제 요즘에 많이 풀어볼 수 있어서 좋네요 ㅋㅋㅋ
최악의 경우에 `O(N^3)`으로 최대 `8,000,000` 혹은 `32,000,000`번 연산을 한다고 생각되었고 이는 시간안에 충분히 수행될 수 있다고 생각했습니다.
1. 각 위치의 정보`(row, col, time, isBomb)`을 관리하는 `Area` 클래스를 만들었습니다.
2. 초기에 폭탄들의 정보는 `isBomb`을 `true`로 놓고 시작했습니다.
3. 시간의 흐름은 1초부터 계산하도록 했고 1초에는 각 자리들의 `time`만 1초 증가시키고 `continue`합니다.
4. 이후 짝수초에는 폭탄이 아닌 모든 자리에 폭탄을 설치했습니다. `new Area(row, col, true)` 
5. `홀수초`에는 해당 자리가 폭탄이면서 생성된지 3초의 시간이 지난 폭탄이면 해당 자리를 `new Area(row, col, false)`로 초기화합니다.
6. 그리고 상하좌우 방향을 확인하며 범위를 벗어나는지 확인하고 폭탄임과 동시에 터져야되는 폭탄일때만 넘어가고 나머지는 다시 새롭게 `new Area(newRow, newCol, false)`로 초기화했습니다.
7. 6의 과정에서 폭탄임과 동시에 3초이상을 갖고 있는 폭탄을 `continue`하게 했는데 이 과정에서 오류를 범했습니다. 옆자리는 아직 늘어난 시간이 셋팅되지 않았으므로 3초가 아닌 2초일때 `continue`하도록 했어야합니다. 오류를 알아채고 해당 로직을 수정했습니다.
1. 잘 풀어놓고 `StringBuilder`에서 개행을 …
> [Ader] BOJ(16918): 봄버맨 - 문제풀이

- src/짱민/14888.py
- src/짱민/16918.py
- src/짱민/거리두기 확인하기.py
다들 하위 입니다.
이런 쌩구현 문제도 감각을 익히는데 조금 괜찮지 않은가요? ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ 모두 고생하셨습니다
매 단계 마다 O(R*C*2) 만큼의 연산을 수행합니다. 브루트 포스에 가깝겠네요
구현 내용 그대로 구현했읍니다... 알고리즘 기법을 사용하지는 않았네요
문제 지문이 이해가 잘 안가더라구요
맨 처음에 1초 쉰다는 것을 잘못 이해해서 3초마다 1초씩 쉬는 것으로 두고 풀어서 잘못된 답을 계속 얻었습니다.
> [ZZANG] BOJ (16918) : 봄버맨- 문제 풀이 #81

- src/밀러/BOJ_16918.py
안녕하세요, 백준 16918 문제풀이를 들고온 밀러입니다 🐱‍🏍
겉보기에는 구현 문제인데, 혹시라도 점화식의 규칙을 가져 시간복잡도를 낮추기를 요구하는 알고리즘 문제일까봐
먼저 시간 복잡도를 생각해봤습니다.
1 <= R, C, N <= 200 이니까 최악의 경우 200^3 = 8,000,000 회의 연산으로,
넉넉하게 2초의 시간 안에 풀릴거라고 안심하고 구현에 접근했습니다.
먼저 지도에서 각 원소를 `.` 또는 `O` 의 문자 대신 폭발까지 몇 초가 남았는지 3 이하의 숫자로 바꿨습니다.
봄버맨이 폭탄을 설치하는 시간과, 폭탄이 설치하는 시간에 규칙성이 있음을 확인했습니다.
n 초 경과했을 때, n 이 짝수이면 폭탄을 설치하고, n 이 3 이상인 홀수이면 폭탄이 폭발합니다.
따라서 시간에 따라 폭탄을 설치하거나, 폭탄을 폭발하는 함수를 각각 `set_on()`, `set_out()` 으로 정의했습니다.
그리고 n 을 1, 2, 3, ... 으로 순회할 때마다 각 원소의 숫자에 -1 을 취하는 함수 `time_out()` 을 정의했습니다.
단, `set_out()` 의 경우 각 원소를 순회하면서 폭발이 일어나면, 주변의 원소 또한 폭발되어 0 으로 초기화됩니다.
그 주변의 원소 또한 폭탄이 위치했는데도 0 으로 초기화되는 바람에 폭발이 일어나지 않는 경우를 피하기 위해,
폭발 시에는 0 이 아닌 -1 로 원소의 값을 할당하고 조건을 좀 더 추가하게 되었습니다.
오랜만에 구현 문제를 만나서 반가웠고, 은근히 코드스쿼드 테스트에서 만났던 소코반하고도 비슷했던 것 같습니다.
좋은 문제 감사합니다 …
> [Miller] BOJ(16918): 봄버맨 - 문제풀이

- src/땃쥐/BOJ_16918.java
- 꽤 많은 시간을 들여서 풀었는데 풀고나니 4시간이 갔습니다.
- 문제 내주셔서 감사합니다.
- 행 열만큼 탐색을 해야합니다. (row * column)
- 게다가 시간만큼 또 탐색해야합니다. (time)
- 폭탄이 설치되어 있으면 자기 자신을 포함해 상하좌우도 다시 살펴 처리해야합니다.
---
- 무슨 알고리즘인지는 신경 안 쓰고 그냥 주어진 요구사항에 맞게만 구현했습니다.
- 뭔가 미세하게 일부분이 제대로 동작되지 않는 부분이 있었는데... 이것때문에 sout문을 돌려서 뭐가 문제인지 찾느라 고생이였습니다. 알고보니 폭발을 처리하는 부분에서, 인접한 폭탄 중에 다음에 터질 폭탄들도 한번에 처리하는 바람에 그 폭탄이 영향을 끼칠 인접 영역들에 영향이 안 갔던 것이였습니다.
```java
private static int row;
private static int column;
private static int time;
private static int[][] bombCounter;
private static int[] rowDiff = {-1, 1, 0, 0};
private static int[] columnDiff = {0, 0, -1, 1};
```
- 행/열/시간/카운터(다음에 터지는 타이밍)
- 상하좌우를 방향을 조절하기 위한 배열
```java
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
StringTokenizer st = new StringTokenizer(br.readLine(), " ");
row …
```
> [땃쥐] BOJ(16918): 봄버맨 - 문제풀이

- src/산토리/거리두기 확인하기.py
- src/산토리/봄버맨.py
안녕하세요. 산토리입니다.
토요일 문제 풀이 업로드합니다~
구현 문제라서 조건에 맞게 구현하는 걸 목표로 충실히 구현했습니다!
1초 이후부터 2,3초의 액션은 주기적으로 계속 반복되므로 1초까지만 초기 상태를 정의해주고
2,3초부터는 while문으로 시간이 다될때까지 실행하도록 했습니다.
초기 상태에서 폭탄 위치를 배열에 저장한 후, 폭발할 때마다 배열에서 꺼내서 폭발 처리를 해주었습니다.
그리고 폭탄이 없는 위치에 폭탄을 설치할 때 다시 폭탄 위치를 기록하고, 폭발 처리를 하고 반복했습니다.
크게 삽질을 안하고 한번에 통과했습니다 !
폭탄 위치를 체크하는 연산이 O(R*C)이 소요되므로 세트당 시간복잡도는 O(R*C)이 될 것 같습니다. 
시간에 비례하여 시간복잡도가 증가할 것으로 보입니다. 단, R, C, N 모두 최대 200이므로 최악의 경우에도
200^3 = 8,000,000으로 통과가 가능할 것으로 보입니다.
> [산토리] BOJ(16918): 봄버맨 - 문제풀이

- src/아더/BOJ_1916_최소비용구하기.java
최단거리 구하기 반갑네요!
다익스트라이므로 `O(E log V)`로 계산됩니다.
`100,000 X log (1,000 ~ 1,000,000)` 이라 1초 안에 가능입니다.
1. 저만 알아볼 수 있는 코드가 많은 것 같아서 코드에 주석을 달아놓았습니다.
2. 모든 `dist[]` 거리 배열을 Integer의 최댓값으로 초기화해줍니다.(최단거리를 갱신하기 위함)
3. `Info`라는 자료구조는 각 정점에 대한 정보를 갖고 있습니다.
4. `Edge`라는 자료구조는 각 간선에 대한 정보를 갖고 있습니다.
5. `우선순위 큐`를 활용하여 다익스트라를 구현합니다. (거리를 기준으로 우선순위 큐를 구현합니다)
6. 큐에서 하나씩 꺼내면서 해당 정점으로 갈 수 있는 최단 거리를 찾았을 때만 `dist배열`을 갱신합니다.
7. `dist[GOAL]`에는 우리가 찾아야 하는 정답이 저장되어 있습니다.
1. 이전에 풀어보았던 문제이며 다익스트라만 사용하면 되는 문제라 삽질은 없습니다.
> [Ader] BOJ(1916): 최소비용 구하기 - 문제풀이

- src/땃쥐/BOJ_1916_1.java
- src/땃쥐/BOJ_1916_2.java
안녕하세요... 문제를 출제해야하는데 알고리즘을 아는게 없어서 뭘 할까 고민했는데
일단 모르는 것들 공부하자는 차원에서 최단거리 알고리즘을 선택하여 알아보기로 결심했습니다.
답을 보고나서도 지금도 정신이 나가는 중입니다.
---
- 접근과정 1의 경우 매번 전체 노드중에서 최소소모비용을 가진 노드를 찾는데 N, 해당 노드 기준으로 확인 및 갱신으로 인해 최악의 경우 대략  n만큼 연결 노드를 일일이 확인해야하기 때문에 O(N^2)으로 알고 있습니다.
- 접근과정 2의 경우 이론상으로 우선순위 큐를 사용하면 O(ElogN)정도 소요되어 더 빠르다고 알고 있습니다.
- 저는 접근과정 1, 2 둘다 풀어봤는데 1이 더 빠르게 나왔습니다. 왜 이게 더 빠른지 모르겠습니다... (232ms)
```java
private static int N; // 노드의 갯수
private static List<List<int[]>> connects; // 연결 노드 및 소요 비용
private static int[] minCosts; // 최소 비용들
private static boolean[] visited; // 방문 여부
```
- N : 노드의 갯수
- connects : 각 노드별로 단방향 연결 노드 및 소요 비용을 int[]로 저장하고 담은 이차원 List입니다.
- minCosts : 각 노드별 최소 소요비용입니다. 이 최소 소요비용은 시작점을 0으로 기준삼습니다.
```java
N = readInt();
minCosts = new int[N+1];
for (int i=0; i<N+1; i++) { …
```
> [땃쥐] BOJ(1916): 최소비용 구하기 - 문제풀이

- .idea/codesquad-algorithm.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- src/산토리/합승 택시 요금.py
안녕하세요.. 산토리입니다.
목요일 문제 풀이입니다..
예전에 풀었던 문제이지만 접근하는데 꽤나 걸렸습니다.. 바로 난이도가 급상승하는 느낌이네요 ..ㅎㅎ
접근 과정은 합승 택시 요금이 최소가 되려면, `(시작점으로부터 합승 도착지점까지의 최소 비용) + (합승 도착지점으로부터 A 집 까지의 최소 비용) + (합승 도착지점으로부터 B 집까지의 최소 비용)`을 구해야 합니다. 
이걸 구하려면 결국은 합승 도착지점을 1~N까지 모두 탐색하면서 최소 비용의 합을 구해보아야 합니다.
즉, 모든 노드간의 최소 비용을 구해야 합니다.
그래프에서 모든 노드의 최단거리를 구하는 알고리즘으로 플로이드-와샬 알고리즘이 있습니다.
- 거리 배열 초기화하기
```python
dist = [[0 if i == j else sys.maxsize for i in range(n + 1)] for j in range(n + 1)]
for fare in fares:
v, w, cost = fare
dist[v][w] = cost
dist[w][v] = cost
```
직접 연결되어있지 않은 부분은, 거리를 무한대로 세팅하고 자기 자신의 거리는 0으로, 나머지는 주어진 정보대로 초기화합니다.
- 최단 경로 조사하기
```python
for k in range(1, n + 1):
for i in range(1, n + 1):
for j in range(1, n + 1):
dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])
```
이 때, 임의의 지점 k에 대해, i->j로 갈 때 k를 거쳐가는 …
> [산토리] Programmers(72413): 합승 택시 요금

- src/아더/Pro_72413_합승택시요금.java
확실히 여러군데 함정이 있는 까다로운 문제였네요 ㅠ_ㅠ
카카오 쉽지 않군요.....
플로이드 워셜이므로 `O(N^3)`로 계산됩니다.
`200 X 200 X 200` 이라 1초 안에 가능입니다.
1. `최단거리`라는 키워드와 `중간지점을 거쳐가면 최단거리가 단축될 가능성`이 있다는 키워드를 보고 `플로이드 워셜 알고리즘`을 떠올립니다. 
2. `모든 거리를 INF로 초기화`합니다. 이 문제에서 `INF를 아무생각없이 설정하면 엣지케이스`에 걸리게 됩니다. 따라서 최댓값을 커버할 수 있도록 `100,001 * n의 값으로 초기화`합니다. `자기 자신의 점은 0으로 초기화`합니다.
3. 문제에서 주어진 거리값을 통해 연결되어 있는 점들은 값을 채워줍니다.
4. 플로이드 워셜 알고리즘을 통해 `dist배열을 채웁니다`.
5. 이 마지막 부분이 보통의 플로이드 워셜 알고리즘 문제들에서는 찾아볼 수 없는 부분이라 고민이 많이 되었습니다. 결국 답을 도출할 수 있는 식을 생각해 정답을 구합니다.
1. 최초에 문제를 보고 `플로이드 워셜 알고리즘`을 떠올렸으나 A와 B의 경로가 겹치면 합승한다는 조건에서 경로에 눈이 돌아가 경로를 기억할 수 없는 `플로이드 워셜 알고리즘을 포기`했습니다.
2. 경로에 눈이 돌아간 저는 `BFS를 통해 최단거리 경로를 구할 수 있지 않을까`라고 생각해보았습니다. 다만 이렇게 구해진 경로에서 `합승 경로를 골라내는 것`이 또 어려울 것 같아 다시 포기하게 되었습니다.
6. 제대로 된 풀이를 제출했으나 INF 거리를 설정하는 부분에서 `Integer.MAX_VALUE`를 사용하면 …
> [Ader] Programmers(72413): 합승 택시 요금 문제 풀이

- src/땃쥐/Programmers_72413.java
- 플로이드-워셜 최단거리 알고리즘은 N회에 거쳐서 자기 자신이 아닌 서로 다른 두 노드에 대해(N-1 * N-2), 자신을 경유하는 비용의 최솟값을 계속 갱신시켜야하므로 시간 복잡도는 O(N^3)이 됩니다.
---
```java
private int[][] minCosts;
public int solution(int n, int s, int a, int b, int[][] fares) {
minCosts = initMinCosts(n, fares);
floyd(n);
return getAnswer(n, s, a, b);
}
```
- `initMinCosts` : 노드의 갯수, 간선정보를 기반으로 최소비용 2차원 배열 초기화
- `floyd` : 플로이드 - 워셜 알고리즘을 기반으로 최소비용 갱신(최적화)
- `getAnswer` : 최소비용이 최적화된 상황에서, 공통 시작점, a의 도착지, b의 도착지가 주어졌을 때 합승 최소비용을 반환
```java
private int[][] initMinCosts(int n, int[][] fares) {
int[][] minCosts = new int[n + 1][n + 1];
for (int i = 1; i <= n; i++) { // 기본 초기화
for (int j = 1; j <= n; j++) {
minCosts[i][j] = (i == j) ? 0 : Integer.MAX_VALUE; // 자기 자신으로 가는 비용은 0, 나머지는 무한
}
}
for (int[] fare : fares) { // fare를 읽고 양방향 비용 초기화 …
```
> [땃] PROGRAMMERS(72413): 합승 택시 요금 - 문제풀이

- src/땃쥐/BOJ_11657.java
안녕하세요. 다음 주 발표였는데 덕분에 세번 연속 최단거리 알고리즘을 풀 수 있어서 준비에 많이 도움된 것 같습니다. 감사합니다.
---
176ms
- 총 노드의 갯수에 해당하는 N번 E개의 간선을 순회하므로 시간복잡도는  O(NE)입니다.
---
- 이 문제의 풀이방식은 벨먼-포드 최단거리 알고리즘입니다.
- 간선 중에 음의 비용을 가진 간선이 있을 경우 다익스트라 알고리즘을 적용할 수 없는데 이러한 경우에 대해서 사용하는 알고리즘이 벨먼-포드 알고리즘을 확인했습니다.
```java
private static int N; // 도시의 갯수
private static int M; // 노선의 갯수
private static int[][] edges; // 간선들
private static long[] dist;
private static final int INF = Integer.MAX_VALUE;
N = readInt();
M = readInt();
edges = new int[M][3];
for (int i=0; i<M; i++) {
int s = readInt();
int e = readInt();
int cost = readInt();
edges[i] = new int[]{s, e, cost};
}
dist = new long[N+1];
for (int i=0; i<N+1; i++) { // 무한으로 초기화
dist[i] = INF;
}
```
- N : 도시의 갯수
- M : 간선의 갯수
- …
> [땃쥐] BOJ(11657): 타임머신 - 문제풀이

- src/제이/week5/BOJ_11657.java
- src/제이/week5/BOJ_1916.java
- src/제이/week5/Programmers_72413.java
안녕하세요 Jay 입니다. 이번주는 역대급으로 문제가 어려웠던 것 같네요..
화요일 첫 문제 부터 저는 손도 못댈정도로 어려워서 결국 답을 참고하였습니다.
그래도 문제 답을 보고 이해한 뒤에 덮어놓고, 혼자 그 답을 구현할 정도가 되어야 스스로 풀었다고 생각해서
이번 문제들도 그렇게 해보려고했지만 답을 보고도, 심지어는 정답을 맞추고도 스스로 이해가 잘 안되었습니다..
그래서 솔직하게 말씀드리면 사실 의욕이 좀 떨어져서 주간에 성실하게 문제를 풀지 못한 것 같습니다..
꾸준히 성실하게 푸는게 목표인 스터디인데, 그렇게 하지 못하여 분위기를 흐린 것 같아 다른 분들께 죄송합니다..ㅠㅠ
노드의 수 : V
간선의 수 : E
시간 복잡도 O(VE)
밸만 포드 알고리즘을 이용하여 풀이하였습니다.
다익스트라 알고리즘을 공부할 때 음수 간선이 있으면 정확한 값이 나오지 않을 수 있고,
밸만 포드 알고리즘이 `음수 사이클`을 구할 수 있는 알고리즘이라고 한 것이 기억났었습니다.
하지만, 구현하는건 또 다른 문제였습니다.
어떻게 하다보니 정답은 맞췄지만, 왜 맞았는지 사실 잘 모르겠네요..
조금 더 공부를 해봐야할 것 같습니다..
감사합니다.
---
이전문제 풀이 및 접근 방법도 첨부합니다.
다익스트라 알고리즘의 시간복잡도를 잘 몰라서 검색해서 찾아봤습니다.
최악의 경우 그래프의 모든 노드간 연결된 간선에 대해 한번씩 작업이 일어나기 때문에
`O(n log n)` 이라고 합니다.
너무 어렵고, 감이 안와서 조금 고민하다가 알고리즘 분류를 확인했습니다.
다익스트라 알고리즘 이라는걸 처음 접해서 공부하고 문제를 풀어봐도 마의 …
> [Jay] BOJ(11657): 타임머신 - 문제풀이

- src/산토리/작업.py
안녕하세요! 산토리입니다.
화요일 문제 풀이 업로드합니다~
문제를 제대로 읽지 않아서... 먼저 수행되어야 하는 작업이 해당 작업보다 앞선 번호로만 이뤄진다는 걸 몰랐습니다. 그래서 정렬을 해야할까 하다가 그냥 모든 작업을 순회하면서 선행조건이 모두 만족된 작업부터 실행하도록 했습니다.
그랬더니 시간 초과가 발생해서 예전에 푼 코드를 참조해보고 문제를 읽다가 조건을 발견했습니다. 
단순하게 순서대로 입력을 받으면서 걸리는 시간을 기록합니다. 순서대로 실행된다고 가정하면 항상 선행 작업이 모두 실행된 상태이므로 선행 작업이 모두 실행되었는지 검사할 필요도 없습니다. 단지 선행작업이 모두 완료되는 시간에 해당 작업이 걸리는 시간을 더해서 기록만 해둡니다. 이런 식으로 어떤 작업의 선행 작업 중 가장 오래걸리는 시간과 해당 작업의 시간을 더해서 모두 기록합니다. 기록한 리스트에서 최댓값이 모든 작업이 완료되는 시각입니다. 
각 선행작업이 최대 N-1개 일 수 있으므로, O(N^2)이 소요될 것 같습니다.
> [산토리] BOJ(2056): 작업 - 문제풀이

- src/아더/BOJ_2110_공유기설치.java
제가 첫 주차 때 발표했던 `매개변수 탐색` 문제네요! 
다들 기억이 안나실때 쯤 되었지만 잘 푸셨길 바랍니다 ㅋㅋㅋㅋ
이분탐색 베이스여서 `O(log N)`입니다!
1. 먼저 정렬을 진행합니다. (집 좌표의 범위를 보고 결정 이분탐색을 사용하기로 결정)
2. `~~의 최댓값`이라는 키워드를 보고 `매개변수 탐색`으로 접근합니다.
3. 문제를 뒤집습니다. -> 거리 X로 했을 때 모든 집 사이사이에 C개의 공유기를 설치할 수  있는가?
4. `매개변수 탐색` 문제를 해결합니다.
1. ^_^
> [Ader] BOJ(2110): 공유기 설치 - 문제풀이

- src/땃쥐/BOJ_2110.java
##
안녕하세요.
모처럼에 기존에 풀었던 개념들을 다시 출제해보고자 이진탐색으로 삥 돌아 문제를 냈습니닷.
요즘 팀프때문에 에너지가 정말 빠르게 고갈되고있습니다. 체력관리 중요합니다... 
---
192ms
- mid값 탐색은 이진 탐색이므로 O(logN)
- mid값을 실제 대입하여 N개의 집을 순회하며 설치가능 공유기 갯수를 계산하는 작업을 수행 (N)
- Total : O(NLogN)
---
```java
int N = readInt(); // 집의 수
int C = readInt(); // 공유기의 수
int[] house = new int[N]; // 집들의 좌표들
for (int i=0; i<N; i++) {
house[i] = readInt();
}
Arrays.sort(house); // 정렬해야 거리 관계를 파악하기 쉬움
int maxDistance = findMaxDistance(N, C, house); // 공유기간 최소거리의 최댓값
System.out.print(maxDistance);
}
```
- 변수 : N (집의 개수) / C(공유기의 수) house(집의 좌표들)
- 집의 좌표들은 오름차순으로 정렬해야 전후관계 파악에 용이하므로 Arrays.sort 메서드로 정렬
- findMaxDistance 메서드로 공유기간 최소거리의 최댓값을 찾는다.
- 출력
```java
private static int findMaxDistance(int N, int C, int[] house) …
```
> [땃쥐] BOJ(2110): 공유기 설치 - 문제풀이

- src/산토리/치킨 배달.py
안녕하세요! 산토리입니다.
토요일 문제 풀이 업로드합니다~
예전에 풀었던 문제라 그런지 조금 생각해보니 아이디어가 바로 떠올라서 실천했습니다.
복잡한 알고리즘보다는 일단 단순한 구현으로 부딪혀봤습니다.
먼저 board를 탐색하면서 치킨집과 집의 위치를 파악합니다.
그 다음 각 치킨집 별로 각 집의 거리를 모두 저장합니다.
그리고 M개의 치킨집을 조합으로 뽑아서 각 집마다 치킨집의 거리 중 가장 짧은 값을 더합니다.
이렇게 더한 도시의 치킨 거리 중 작은 값을 반환합니다. 
board를 탐색해서 정보를 받는 부분은 우선 O(N^2)에 완료되는데...
조합을 뽑는 과정에서 치킨 집이 최대 13개이고, M이 6일 때 경우의 수가 최대 800만 개 정도 됩니다.
이 때 집의 개수*치킨집의 개수만큼 순회하는데, 집은 최대 2N, 치킨집은 6개이므로 대략 600번입니다.
이러면 800만 * 600이 되어 시간 초과가 날 것 같은데 잘 통과하네요... 미스테리입니다.
> [산토리] BOJ(15686): 치킨 배달 - 문제풀이

- src/아더/Pro_84512_모음사전.java
오늘 문제는 전 주에 풀던 문제들보다는 난이도가 조금 낮은 느낌이네요.
두 문제를 고민하다가 이걸 출제했는데 다른 걸 낼껄 그랬나봐요....
다음 출제턴을 기대해주세요!!
어마무시할거 같네요.... 정확한 시간복잡도는 못구하겠어요 ㅠㅠ
1. 먼저 `A, E, I, O, U`로 만들 수 있는 단어의 모든 조합을 리스트에 저장합니다.
2. 리스트에서 중복을 제거하고 정렬을 수행합니다.
3. `.indexOf() + 1`을 통해 답을 출력합니다.
1. 정해진 갯수를 뽑는 것이 아닌 1 ~ 5개까지 뽑는 로직을 조금 고민했습니다.
4. 그리고 현재 풀이도 시간복잡도상 유리한 풀이는 아닌 것으로 생각되네요 ㅠㅠ
> [Ader] Programmers(84512): 모음사전 - 문제풀이

- src/산토리/모음 사전.py
안녕하세요! 산토리입니다.
화요일 문제 풀이 업로드합니다~
크게 삽질을 하지 않았네요!!
사전 순으로 모든 단어를 나열한다음 원하는 단어를 찾는 식으로 했습니다. 재귀를 통해서 모든 경우의 수를 찾을 수도 있겠지만 그냥 python에서 제공하는 product를 썼습니다. 
중복 순열이므로 O(N^M)입니다. (N: 단어의 최대 자릿수, M: 알파벳 후보의 수)
> [산토리] Programmers(84512): 모음사전 - 문제풀이

- src/제이/week7/Programmers_84512.java
단어의 길이가 N 이라면, O(N) 입니다
_ = 0
A = 1
E = 2
I = 3
O = 4
U = 5
A____ = 1
AA___ = 2
AAA__ = 3
**\> AAAA_ = 4**
AAAAA = 5
AAAAE = 6
AAAAI  = 7
AAAAO = 8
AAAAU = 9
**\> AAAE_  = 10**
AAAEA = 11
AAAEE = 12
AAAEI = 13
AAAEO = 14
AAAEU = 15
**\> AAAI_ = 16**
표시된 문자들을 살펴보면, 두 문자들 사이에는 5번째 자리가 중가할때 마다 1 씩 증가합니다.
그리고 4번쨰 자리는 증가할 때 마다 6씩 증가합니다.
이를 보면 `AEIOU 5번` + `_ 1번` 인것을 알 수 있었습니다.
그러면 3번째 자리는 `4번쨰 자리까지의 경우의 수` * 5 + 1 으로 구할 수 있습니다.
그래서 다음과 같이 자리수가 증가할 때 마다 증가하는 경우의 수를 구할 수 있습니다.
1번째 자리 : 781
2번째 자리 : 156
3번째 자리 : 31
4번째 자리 : 6
5번째 자리 : 1 
처음에는 모든 경우의 수를 배열에 담아뒀다가, 해당 인덱스를 반환해줘야 하나 생각했는데
시간적으로도, 공간적으로도 최악의방법인것 같아서 넘어갔습니다.
5 + 1 번 이라는 규칙을 알아내기가 너무힘들었습니다.
> [Jay] Programmers(84512): 모음사전 - 문제풀이

- src/밀러/BOJ_5582.py
이번주에 미루고 미루다가 일요일 밤에 한꺼번에 풀었네요.. 죄송합니다 ㅠㅠ
두 개의 문자열의 길이 m, n 에 대해 O(mn) 입니다.
공통 부분 문자열은 유명한 알고리즘인 것을 알았지만 한번도 풀어본 적이 없었습니다.
다만, 함부로 덤볐다가는 어차피 못풀 것이라는 것을 알고 있어서 빠르게 구글링을 했습니다.
워낙 유명한 알고리즘이어서 그런지 GeeksForGeeks 에도 설명이 있더라구요!
<https://www.geeksforgeeks.org/longest-common-substring-dp-29/>
덕분에 공통 부분 문자열 외에도 공통 부분 부분수열도 공부하게 되었습니다.
알고나면 간단할 수 있는 알고리즘인데, 영감을 많이 얻게 되는 알고리즘인 것 같습니다.
감사합니다 짱민!
> [Miller] BOJ(5582): 공통 부분 문자열 - 문제풀이

- src/땃쥐/BOJ_5582.java
---
1번 문자열 길이 N
2번 문자열 길이 M이라 할 때
O(NM) 입니다.
---
```java
// 공통 길이 2차원 배열
int[][] dp = new int[length1 + 1][length2 + 1];
/**
* i행 : 1번 문자열의 i번째 문자열까지
* j열 : 2번 문자열의 j번째 문자열까지
* dp[i][j] : 비교했을 때 공통 길이
*/
int max = 0;
for (int i = 1; i <= length1; i++) {
for (int j = 1; j <= length2; j++) {
if (str1.charAt(i - 1) == str2.charAt(j - 1)) { // 문자가 서로 일치할 때
dp[i][j] = dp[i - 1][j - 1] + 1;
max = Math.max(max, dp[i][j]);
}
}
}
```
- dp : 공통길이를 저장하는 2차원 배열입니다.
- i행 : 1번 문자열의 i번째 문자까지
- j열 : 2번 문자열의 j번째 문자까지
- dp[i][j] : 비교했을 때 공통 길이
- 예) 문자1을 abc, 문자2를 bcde라고 했을 때
- dp[1][1]은 a와 b를 비교했을 때 공통 길이 = 0
- dp[1][2]는 a와 bc를 비교했을 때 공통 길이 = 0
- dp[2][1]은 ab와 b를 비교했을 때 공통 길이 = a와 _를 비교했을 때의 공통길이에서 다음 문자인 1
- dp[3][2]는 abc와 bc를 비교했을 때 공통 길이 = ab와 b를 비교했을 때 공통길이에서 다음 문자인 c가 일치하므로 1 증가
> [땃] BOJ(5582): 공통 부분 문자열 - 문제풀이

- src/제이/week7/BOJ_5582.java
- src/제이/week7/Programmers_84512.java
문자1의 길이 = n
문자2의 길이 = m
O(nm) 입니다.
pd 를 통해 문자들의 각각의 자리끼리 비교하여 같은지 확인합니다.
연속된 숫자가 있으면, 그 길이만큼 카운팅 합니다.
제일 긴 부분집합부터 잘라서 비교하면서, 길이가 같으면 출력하면 되겠다고 생각했습니다.
그런데 계속 시간초과가 나서 고민하다가, 약간의 힌트를 얻었고 DP를 적용하여 풀 수 있었습니다.
> [Jay] BOJ(5582): 공통 부분 문자열 - 문제풀이

- src/밀러/PROGRAMMERS_72411.py
이번주에 미루고 미루다가 일요일 밤에 한꺼번에 풀었네요.. 죄송합니다 ㅠㅠ
O(orders 배열의 길이 X  order 의 길이) 또는 O(courses X 모든 조합의 개수) 로, O(n^2) 쯤 될 걸 같습니다.
LCS (Longest Common Subsequnece) 로 접근해야할지, 위상 정렬로 접근해야할지 고민했는데
각 사람의 주문 별로 DFS 를 적용하고 백트래킹으로 가능한 모든 조합의 개수를 체크하면된다는 것을 알게되었습니다.
백트래킹으로 가능한 모든 조합의 개수 (count) 를 딕셔너리에 저장하고,
다시 딕셔너리에서 조합을 꺼내 문제에서 요구하는 최대 카운트의 조합을 반환합니다.
> [Miller] PROGRAMMERS(72411): 메뉴 리뉴얼 - 문제풀이

- src/산토리/메뉴 리뉴얼.py
- src/산토리/모음 사전.py
안녕하세요! 산토리입니다.
늦었지만 ㅠㅠ 토요일 문제 풀이 업로드합니다~
비교적 수월하게 풀렸습니다! 
모든 메뉴 구성의 코스 수에 따라 조합을 가지고 Counter에 담아서 2번 이상 등장한 것들만 추려서 정답에 담는 식으로 했습니다. 
내부적으로 조합을 해서 시간 복잡도 계산이 복잡하네요... O(n!)일 것 같은데 표본이 굉장히 적어서 괜찮을 것 같습니다.
> [산토리] PROGRAMMERS(72411): 메뉴 리뉴얼 - 문제풀이

- src/아더/Pro_72411_메뉴리뉴얼.java
깔끔한 풀이를 위해 우선순위큐를 사용하는 해답을 참고했습니다.
해답을 조금 더 탐구해보겠습니다.
우선순위큐를 사용했습니다.
1. 모든 후보를 구한 뒤 우선순위 큐에서 하나씩 꺼냅니다.
> [Ader] PROGRAMMERS(72411): 메뉴 리뉴얼 - 문제풀이

- src/제이/week7/BOJ_5582.java
- src/제이/week7/Programmers_72411.java
- src/제이/week7/Programmers_84512.java
이번 문제는 제가 결국 못 풀어서, 여러분들의 좋은 풀이를 보며 조언 받고싶습니다 ㅠㅠ
----
> [Jay] Programmers(72411): 메뉴 리뉴얼 - 문제풀이

- src/아더/BOJ_7576_토마토.java
오랜만에 풀어보는 BFS 문제였네요.
각 줄마다 설명을 주석으로 달아놓았습니다.
전체적으로 `MultisourceBFS`로 풀었습니다.
BFS 이므로 시간복잡도는 `O(N^2)`일 듯 합니다.
1. 먼저 토마토의 각 위치를 큐에 담아줍니다.
2. 이후 `MultisourceBFS`를 통해 해결합니다.
1. 마지막에 정답 출력시 -1을 해주지 않아 잠깐 고민했습니다.
2. -1을 해준 이유는 각 퍼지는 값을 원래 위치의 +1씩 해주었는데 최초위치가 1이기 때문입니다.
> [Ader] BOJ(7576): 토마토

- src/땃쥐/BOJ_7576.java
답을 보면서 풀더라도... 일단 배웠던 개념들 다시 복습차원에서 했던 주제들에 해당하는 문제를 풀어보기로 결심하고 BFS문제를 출제 했습니다
모든 칸에 대한 부패로직을 수행해야하므로 O(MN) 정도 될 것 같습니다.
- bfs 로직을 이코테 책을 보면서 다시 확인하고 실제로 따라 치면서 실습했습니다.
```java
private static final int[] DIRECTION_X = {0, 0, -1, 1}; // 상,하, 좌,우
private static final int[] DIRECTION_Y = {-1, 1, 0, 0};
private static int M; // 가로
private static int N; // 세로
private static int[][] storage; // 창고
initStorage();
bfs();
System.out.print(answer());
}
```
- initStorage
- bfs : storage를 탐색해서 토마토 숙성 로직 수행
- answer() : storage를 읽고 정답을 찾아냄
- 출력
```java
private static void bfs() {
Queue<int[]> queue = new LinkedList<>();
for (int i = 0; i < N; i++) {
for (int j = 0; j < M; j++) {
if (storage[i][j] == 1) { // 익은 토마토이면 큐에 좌표를 삽입
queue.offer(new …
```
> [땃] BOJ(7576): 토마토

- src/산토리/최소 스패닝 트리.py
- src/산토리/토마토.py
안녕하세요! 산토리입니다.
단순한 BFS로 풀어보려고 했는데 시간초과가 나서 해결을 못했습니다 ㅠㅠ
내일까지 풀어서 재업로드하겠습니닷~~
> [산토리] BOJ(7576): 토마토

- src/제이/week9/BOJ_1197.java
- src/제이/week9/BOJ_7576.java
> [Jay] BOJ(7576): 토마토 - 문제풀이

- src/밀러/BOJ_7576.py
문제풀이를 늦게 올려서 죄송합니다 😭
알고리즘을 오랜만에 풀어서 큐로만 풀이 했다고 생각했는데, 알고보니 BFS 였습니다.
큐에는 토마토에 해당하는 `(row, col, day)` 로 원소가 삽입되는데,
큐에서 익은 토마토를 하나 추출한 뒤 다음 날에 익은 토마토를 큐에 넣을 때는 `(row, col, day + 1)` 로 큐에 삽입했습니다.
그리고 큐에서 모든 원소가 추출되고 난 뒤에는,
마지막에 모든 토마토에 대해 익지 않는 토마토가 있는지 검사합니다.
O(N * M) 의 시간 복잡도를 가집니다.
> [Miller] BOJ(7576): 토마토 - 문제풀이 추가

- src/제이/week9/BOJ_1197.java
간선의 수 : V
O(V)
프림 알고리즘을 공부하여 적용하였습니다.
접해보지 못한 유형의 문제라, 최소 스패닝 트리를 구할 수 있는 프림 알고리즘을 공부하였습니다
> [Jay] BOJ(1197): 최소 스패닝 트리 - 문제풀이

- src/땃쥐/BOJ_1197.java
크루스칼 알고리즘을 사용했습니다.
- 신장트리 : 하나의 그래프가 있을 때 모든 노드를 포함하면서 사이클이 존재하지 않는 부분 그래프
- findParent : 최상위 부모 찾기
- union : 노드의 부모를 통합.
-  무방향 간선 기준 사이클 발생여부 판단 : 간선의 시작, 끝 노드의 상위 부모가 서로 같으면 사이클이 발생한 것
- 크루스칼 : 모든 간선들에 대해서, 사이클이 발생하지 않는 간선들을 신장트리로
---
> [땃] BOJ(1197): 최소스패닝트리

- src/아더/BOJ_9251_LCS.java
저번의 `substring`에 이어 이번에는 `sequence`문제입니다!
추가 문제이므로 풀지 않으실 분들은 안 푸셔도 됩니다!
DP이므로 `O(N^2)` 입니다.
1. 점화식에 따라 풀이하게 됩니다.
1. 반복문의 범위를 항상 조심합시다!
> [Ader] BOJ(9251): LCS

- src/아더/BOJ_1197_최소스패닝트리.java
최소 스패닝 트리에 대해서 공부하고 `크루스칼 알고리즘`을 사용해 풀이하려고 시도했습니다.
따라서 `Union, Find`알고리즘을 구현해서 풀이를 하려고 했습니다.
크루스칼이므로 시간복잡도는 `O(E log E)`일 듯 합니다.
1. 모든 간선에 대해 오름차순으로 정렬했습니다.
2. 각 간선들에 대해 사이클이 생기지 않는다면 최소스패닝트리에 추가합니다.
3. 추가하는 과정에서 가중치를 계속 더해줍니다.
4. 마지막으로 answer을 출력해줍니다.
1. 7%에서 ㄱㅖ속 틀렸습니다.
2. 제발 저에게 도움을 주세요 선생님들 ㅠ_ㅠ
> [Ader] BOJ(1197): 최소스패닝트리 풀이중 ㅠ_ㅠ

- src/땃쥐/BOJ_1932.java
- 매 순간 그 시점까지의 최대 합을 저장하고 재사용하므로 DP알고리즘입니다.
- 매층마다 각 각의 칸을 한번씩 계산해야합니다.
- n의 값이 증가함에 따라 1, 1+2, 1+2+3, ... n(n+1)/2번을 계산해야할테고... 시간복잡도는 O(n^2/2) 정도 될듯합니다.
```java
int n = readInt();
int[][] maxNumbers = initMaxNumbers(n);
calculateEachMaxNumbers(n, maxNumbers);
int bottomMax = getBottomMax(n, maxNumbers);
System.out.print(bottomMax);
}
```
- readInt : 정삼각형의 한변의 길이를 입력받습니다
- maxNumbers : 각 층의 각 좌표별로 그 시점까지 도달했을 때 산출할 수 있는 최대 합을 저장하는 배열입니다.
- calculateEachMaxNumbers : 계산 로직
- bottomMax : 맨 아랫층 배열의 최댓값
```java
private static int[][] initMaxNumbers(int n) {
int[][] maxNumbers = new int[n +1][];
for (int i = 0; i< n +1; i++) {
maxNumbers[i] = new int[i+2];
}
return maxNumbers;
}
```
- 층수는 n인데, 계산의 편의를 위해 그 보다 위에 가상의 층을 하나 둬서 n+1층으로 …
> [땃쥐] BOJ(1932): 정수 삼각형 - 문제풀이

- src/아더/BOJ_1932_정수삼각형.java
DP로 풀이했기 때문에 `O(N^2)`입니다.
DP로 접근했습니다.
1. 아래의 점화식을 통해 해결했습니다.
```java
for (int i = 1; i < triangle.length; i++) {
for (int j = 0; j < triangle[i].size(); j++) {
if (j == 0) DP[i][j] = DP[i - 1][j] + triangle[i].get(j);
else if (j == triangle[i].size() - 1) DP[i][j] = DP[i - 1][j - 1] + triangle[i].get(j);
else DP[i][j] = triangle[i].get(j) + Math.max(DP[i - 1][j], DP[i - 1][j - 1]);
}
}
```
1. X
> [Ader] BOJ(1932): 정수삼각형 - 문제풀이

- src/제이/week10/BOJ_14503.java
- src/제이/week10/BOJ_1932.java
n * n 크기의 배열에 DP 를 이용하여 풀었기 때문에 O(N^2) 가 될 것 같습니다.
기본적으로 DP 를 활용하여 풀이하였습니다.
합삼각형의 부모 노드의 값은 자식 노드들의 합 중에 큰 합을 넣는 방식으로 풀이하였습니다.
```java
private static int calcSumRecursive(int h, int i) {
if (h == n - 1) return sum[h][i];
if (sum[h][i] == null) {
sum[h][i] = Math.max(
calcSumRecursive(h + 1, i) + tree[h][i],
calcSumRecursive(h + 1, i + 1) + tree[h][i]
);
}
return sum[h][i];
}
```
합삼각형의 제일 위 부터 채워나가는 방식으로 했었는데, 
이 방식으로 하니 기존 값보다 더 큰 값이 있으면 덮어써줘야 해서 DP 를 활용할 수 없었습니다.
그래서 고민하다가 검색하여 힌트를 얻어서, 아래쪽부터 채워나가는 방식을 적용하여 풀이할 수 있었습니다.
> [Jay] BOJ(1932): 정수 삼각형 - 문제풀이

- src/땃쥐/BOJ_14503.java
- 안녕하세요. 골드5라 겁 먹었긴한데 구현문제라서 재미있게 풀 수 있었습니다. 구현은 언제나 꿀잼입니다.
---
- O(NM) 정도 추정됩니다.
- 이 풀이 기준으로는 128ms 정도 나옵니다.
```java
public static void main(String[] args) throws IOException{
Robot robot = initRobot();
int result = robot.run();
System.out.print(result);
}
```
- initRobot : 입력을 기반으로 로봇을 생성합니다.
- robot.run() : 로봇이 청소하고 청소한 칸의 갯수를 반환합니다.
- 결과를 출력합니다.
```java
private static Robot initRobot() throws IOException {
int N = readInt();
int M = readInt();
int[][] map = new int[N][M];
boolean[][] cleaned = new boolean[N][M];
int y = readInt();
int x = readInt();
int d = readInt();
for (int i=0; i<N; i++) {
for (int j=0; j<M; j++) {
map[i][j] = readInt();
}
}
return new Robot(x,y,d, map, cleaned);
}
```
- 로봇의 초기 위치, 방향, 지도 정보, 청소기록정보 초기상태를 바탕으로 로봇을 초기화합니다.
- 불필요한 인자가 좀 섞여있는 감이 있긴한데... 그냥 한 방에 초기화 …
> [땃쥐] BOJ(14503): 로봇청소기 - 문제풀이

- src/밀러/BOJ_14503.py
안녕하세요, BOJ 14503 풀이를 들고온 Miller 입니다 😀
별다른 알고리즘 없이 구현으로 풀었습니다.
로봇 청소기가 움직이는 지점과 방향을 주어진 평면의 조건 (이미 청소한 지점, 벽 등) 에 따라 달라지도록 구현했고,
문제를 풀이하는 과정에서 다음 지점과 방향을 계산할 때 실수를 많이한 점이 아쉽습니다.
평면의 넓이에 따라 로봇 청소기의 이동 횟수가 결정되니까 시간 복잡도는 O(rc) 가 될 것 같습니다.
> [Miller] BOJ(14503): 로봇 청소기 - 문제풀이

- src/땃쥐/BOJ_1068.java
- 노드간 관계를 어떻게 맺어줄지 삽질을 좀 했던 것 같습니다.
- 상황을 간단하게 하고자, 객체를 정의하고 부모-자식간 양방향 참조를 하도록 하였습니다.
---
```java
initNodes();
setParents();
detachNode();
int numberOfLeafNodes = numberOfLeafNodes();
System.out.print(numberOfLeafNodes);
}
```
- 노드 초기화
- 각 노드별 부모 설정
- 입력받은 노드를 트리에서 분리
- 리프노드의 갯수를 세서 출력
```java
private static void initNodes() throws IOException {
N = readInt();
nodes = new Node[N];
for (int i = 0; i < N; i++) {
nodes[i] = new Node(i);
}
}
```
- 노드는 자신의 번호를 상태로 가짐
- 부모를 가짐
- 자식 노드 List를 가짐
- 분리되었는지 여부를 상태로 가짐(여기서는 루트 노드 한정으로 생각)
```java
private static void setParents() throws IOException {
for (int i = 0; i < N; i++) {
int parentNodeNumber = readInt();
if (parentNodeNumber >= 0) {
nodes[i].changeParent(nodes[parentNodeNumber]);
} …
```
> [땃쥐] BOJ(1068): 트리 - 문제풀이

- src/제이/week11/BOJ_1068.java
노드의 개수 N
O(N)
각 노드는 자식 노드를 가지도록 하였습니다.
그리고 특정 노드를 제거하는 로직을 구현하기 위해서 두 가지 작업을 합쳐서 구현하였습니다.
- 해당 노드의 자식 노드 참조 제거
- 해당 노드 비활성화
각 노드는 자식 노드에 대한 참조를 Set 으로 갖고있어서, `clear()` 메소드로 모두 제거했습니다.
그래고 해당 부모도 제거되어야하나, 제거를 위해서는 해당 부모 노드를 갖고있는 노드를 찾아야 하는 작업이 필요했었습니다.
그래서 자기 자신을 비활성화 하는 로직을 추가하는 방식으로 구현하였습니다.
```java
class Node implements Iterable<Node> {
private final Set<Node> childs;
private final int index;
private boolean isActive = true;
public Node(int index) {
childs = new HashSet<>();
this.index = index;
}
public int getIndex() {
return index;
}
public boolean isActive() {
return isActive;
}
public void addChildNode(Node node) {
childs.add(node);
}
public boolean hasChild() {
if (childs.isEmpty()) {
return false;
}
for (Node child : childs) {
if (child.isActive()) {
return true;
}
}
return false; …
```
> [Jay] BOJ(1068): 트리 - 문제풀이

- src/아더/BOJ_1068_트리.java
새로운 방법으로 풀이해보려 했으나 익숙한 방법으로 풀었네요.
최대 O(N)일 것 같습니다.
1. 먼저 지워야되는 해당 노드와 그 자식노드들을 모두 지웁니다.
2. 1의 과정은 재귀함수를 통해 처리됩니다.
3. 그 이후에는 부모노드의 자식노드에 지워야되는 노드가 포함되어 있는지를 확인하고 처리해줍니다.
4. 최종적으로 리프노드의 갯수를 계산합니다.
1. 새롭게 객체를 만들어서 해결하려고 했으나 입력받을 때 초기화 안되는 문제로 인해 코드가 지저분해져 포기했습니다.
2. dfs를 의식하고 풀어보려했으나 미궁에 빠져 포기했습니다.
> [Ader] BOJ(1068): 트리 - 문제풀이

- src/밀러/BOJ_1068.py
안녕하세요, 백준 트리 문제 풀이를 들고온 Miller 입니다 😀
이 문제를 풀 때, 무의식적으로 3가지 잘못된 가정을 하고 접근하는 바람에 코드를 엄청 고쳤습니다.
1. 이진 트리로 구성
2. 노드의 순서에 따라 트리가 구성된다고 가정
3. 항상 자식 노드가 부모 노드보다 뒤에 있다고 가정
결과적으로는 모두 아니었고, 트리의 자식 노드를 설정할 때
노드의 객체가 아니라 인덱스 숫자로만 설정해도 된다는 것을 알고 문제를 풀이했습니다.
dfs 를 활용해 모든 노드의 개수만큼 순회를 하기 때문에 O(N)!
트리 문제인만큼 방문을 체크할 필요없이 노드의 개수만큼만 순회해서 깔끔하네요.
> [Miller] BOJ(1068): 트리 - 문제풀이

- src/밀러/PROGRAMMERS_43162.py
안녕하세요, 프로그래머스 - 네트워크 문제 풀이를 들고온 Miller 입니다!
저희가 스터디를 시작하면서 맨 처음에 풀었던,
connected components 개수를 구하는 문제와 거의 동일하게 풀었던 것 같습니다.
처음에 인접 행렬을 인접 그래프로 바꾸는 부분을 제외하고는 풀이도 거의 똑같은 것 같아요!
지금 다시 보니 그때는 stack 으로 풀이를 했고, 이번에는 recursion 으로 풀었네요 ㅋㅋ
인접리스트에서 최종적으로 모든 정점을 한번씩 방문하고, 모든 간선을 한번씩 검사하므로
시간복잡도는 O(n+e) 이겠지만, 먼저 인접행렬을 순회하므로 O(n^2) 이 될 것 같아요!
> [Miller] PROGRAMMERS(43162): 네트워크 - 문제풀이

- src/땃쥐/Programmers_43162.java
```java
public int solution(int n, int[][] computers) {
int answer = 0;
int[] parents = initParents(n);
unionAll(n, computers, parents);
answer = countRoots(n, answer, parents);
return answer;
}
```
- 최상위 부모를 찾는 findParent 함수
- 두 집합의 최상위 부모를 같은 것으로 통합하는 union 메서드를 활용했습니다.
```java
private int countRoots(int n, int answer, int[] parents) {
for (int i = 0; i< n; i++) {
if (parents[i] == i) {
answer++;
}
}
return answer;
}
```
- 최상위 부모를 저장합니다.
- 초기 상태에서 최상위 부모는 자기 자신
```java
private void unionAll(int n, int[][] computers, int[] parents) {
for (int i = 0; i< n; i++) {//0,1,2,...n-1 컴퓨터에 대하여
for (int j = 0; j< n; j++) { // 0,1,2,...j-1과 연결상태를 확인
if (i!=j && computers[i][j] == 1) { // 연결되어있는가?
union(parents, i, j);
}
}
}
}
```
- 연결상태를 싹 확인합니다.
- 자기 자신이 아닌 것들과 연결상태를 확인하여 연결된 상태면 최상위 부모를 더 작은 것으로 …
> [땃쥐] Programmers(43162) : 네트워크

- src/아더/BOJ_11659_구간합구하기4.java
> add : BOJ 11659 구간합구하기4 풀이 추가

- src/아더/BOJ_15651_N과M3.java
> add : BOJ 15651 N과M3 풀이 추가

- src/아더/INF_최대매출.java
> add : 최대매출 풀이 추가
