src/밀러/BOJ_11724.py
안녕하세요, #1 문제를 업로드한 Miller 입니다 😀
산토리가 푼 방식과 비슷하게, DFS 를 이용해 connected components 의 개수를 파악하는 방식으로 풀이했습니다. 
```python
for vertex in range(1, n + 1):
if visited[vertex - 1]:
continue
answer += 1
stack.append(vertex)
visited[vertex - 1] = True
while stack:
now: int = stack.pop()
for dest in graph[now]:
if not visited[dest - 1]:
stack.append(dest)
visited[dest - 1] = True
```
`stack` 은 방문 예정인 `vertex` 가 대기하는 스택이고, `visited` 는 방문 도장을 찍는 배열입니다.
각 원소를 순회하면서 방문하지 않은 `vertex` 인 경우 `stack` 에 추가합니다.
`while` 문 안에서 `stack` 의 원소가 없을 때까지 `vertex` 를 추출해,
`graph` 에서 해당 `vertex` 에서 출발하고 목적지인 `dest` 를 순회합니다.
순회하면서 이미 방문한 `dest` 인 경우 건너뛰고,
방문하지 않은 `dest` 만 `stack` 에 추가하고 `visitied` 배열에 방문 도장을 찍습니다.
백준에서 문제를 많이 안풀어봤는데, 백준에서 Python3 로 실행하면 채점이 굉장히 느리고 시간 초과가 떴습니다.
그런데 PyPy3 로 실행하니까 깔끔하게 맞았다고 뜨네요..
=> [Miller] #1 20220302 BOJ_11724 풀이 제출

src/산토리/기차가 어둠을 헤치고 은하수를.py
안녕하세요. 산토리입니다.
문제 풀이 업로드합니다.
특별한 알고리즘보다는 단순 구현이라고 생각하여 각 좌석을 dictionary로 만들어 풀었습니다. 최대 요청이 10만개이고 제일 오래 걸리는 연산인 shift할 때도 좌석의 개수가 20번밖에 안걸려서 시간초과는 나지 않을 것이라고 생각했습니다. 
좌석에 승차하거나 내릴 때는 그냥 key값으로 조회하여 없으면 태우고, 있으면 삭제하는 방식을 택했습니다. 한 칸씩 밀거나 당길 때는 for문을 돌면서 한 칸씩 옮겨주었습니다.
각 기차의 좌석을 만들어주는 작업: O(n*x), n: 기차의 개수, x: 좌석의 개수
요청을 처리하는 데 걸리는 시간: O(m*x), m: 요청의 개수, x: 좌석의 개수
계속 맞왜틀을 반복했는데... 마지막에 set()을 통해서 탑승 상태의 중복을 제거하고 답을 출력하는 부분이 있었는데, 좌석에 해당하는 dictionary의 key값이 정렬이 되어있지 않기 때문에 중복을 걸러낼 때 잘 걸러지지 않는다는 걸 다른 블로그 풀이를 참고하다 알게 됐습니다.. 사소하지만 찾기 어려운 실수였어서 깨달음을 얻어갑니다..
이 문제를 비트마스킹으로도 풀 수 있다고 하는데 비트마스킹에 대해서 공부해보면 좋을 것 같습니다.
=> [산토리] BOJ(15787): 기차가 어둠을 헤치고 은하수를 - 문제풀이

src/산토리/기차가 어둠을 헤치고 은하수를.py, src/산토리/수들의 합 2(수정).py, src/산토리/수들의 합 2.py, src/산토리/예산.py
안녕하세요. 산토리입니다.
문제 풀이 업로드합니다.
수열의 항 개수가 최대 10000개이고, 시간 제한이 0.5초인 점을 감안하여 O(nlogn)이내로 통과해야되겠다고 생각했습니다.
순서를 지켜야하기 때문에 정렬 등을 활용할 수 없고, 한 항을 고정하고 더하는 일반적인 브루트포스를 활용하면 O(n^2)이 됩니다.
그래서 이를 개선하는 대표적인 알고리즘인 투 포인터 방식으로 접근했습니다.
left, right의 두 포인터를 놓고 left를 고정한 상태에서 right를 전진시키다가 주어진 목표값보다 커지면 left를 한칸 이동하고 다시 비교해보는
식으로 각 포인터가 한 번만 순회해도 모든 경우의 수를 탐색할 수 있도록 하였습니다.
처음에 투 포인터로 접근했는데 시간 초과가 발생했습니다. 틀린 코드도 같이 첨부하였는데, 투 포인터로 접근은 했지만 탐색 결과를 활용하지 않고 M을 초과하면 다시 left, right 포인터를 같은 자리에서 시작했던 것이 패착이었던 것 같습니다. 이렇게 되면 left는 한 번만 탐색하지만 right는 계속 갔던 곳을 돌아오기 때문입니다. 
각 포인터가 수열을 한번씩만 탐색하므로 O(n)
=> [산토리] BOJ(2003): 수들의 합 2 - 문제풀이

src/밀러/BOJ_2003.py
안녕하세요 BOJ 2003 풀이를 들고 온 Miller 입니다 😀😀
투 포인터로 풀기로 마음을 먹었는데, 다른 분들과 달리 원소를 순회하면서
각 인덱스마다 짝수/홀수로 윈도우를 만들고 윈도우를 좌우로 넓혀가면서 문제를 풀이했습니다.
제 생각엔 O(n^2) 인데 브루트포스로 원소를 순회하는 경우보다 검사하는 횟수가 적어 풀리지 않았을까 생각합니다.
처음에 모든 원소를 정렬해놓고 풀었는데, 알고보니 정렬하면 안되는 문제더라구요.
다시 풀면서 58% 에서 틀리는 결과가 나와서, 엣지 케이스가 나기 쉬운 경우를 대입해 해결했습니다.
=> [Miller] BOJ(2003): 수들의 합 2 - 문제풀이

src/제이/week2/BOJ_2003.java
안녕하세요 Jay 입니다.
이번문제는 생각보다 간단하게 풀렸습니다..!
제 풀이의 시간복잡도는 `O(nLog(n))` 입니다.
지난주에 산토리가 1초에 약 1억번의 연산할 수 있다고 가정하고 시간복잡도를 계산하면 된다고 하셨는데,
이번 문제는 제한 시간이 0.5초이기 때문에 이번 문제에서는 약 `50,000,000`번의 연산내에 풀이해야합니다.
이번 문제에서 n의 최대값은 10,000 이고 `nLog(n)`의 시간복잡도임을 고려하면, 
약 `40,000`번의 연산을 한다고 생각할 수 있습니다.
그래서 시간내에 풀이할 수 있을것이라 생각했습니다!
\+ 다 풀고 보니 땃쥐는 누적합으로 풀이하셨던데, 누적합이 시간복잡도를 줄일 수 있는 좋은 풀이방법인 것 같다는 생각이드네요..!
기본 풀이는 두 포인터 방식으로 풀었습니다.
그리고 탈출 조건을 최대한 많이 붙여서 반복문을 최대한 빨리 탈출할 수 있도록 신경썼습니다.
(그런데 그렇게 큰 시간 차이는 나지 않더라구요!)
```java
for (int p1 = 0; p1 < numbers.length; p1++) {
int sum = 0;
int num1 = numbers[p1];
// 첫 포인터의 숫자가 합보다 크면 더 탐색할 필요 없음
if (num1 > m) continue;
// 첫 포인터의 숫자가 합과 같으면 count 하고, 더 탐색할 필요 없음
if (num1 == m) {
count++;
continue;
}
sum += num1;
for (int p2 = p1 + 1; p2 < numbers.length; p2++) {
int num2 = …
```
=> [Jay] BOJ(2003): 수들의 합 2 - 문제풀이

src/땃쥐/BOJ_1463.java
예전에 풀어보고 답을 찾아봤던 문제인데 그대로 이해가 안 가는 감이 많습니다.
---
DP알고리즘에 의해 각 값들은 1회씩 계산되므로, O(N) 입니다.
---
- 처음 접할 때 도저히 스스로 풀 자신이 없는 문제였습니다.
- DP가 한번 계산한 것들은 값을 저장한다는 알고리즘이긴한데 그것만으로는 이 문제를 푸는데 제 실전 경험이 부족해서 바로 와닿지 않았습니다.
---
그림을 그려보고 각  숫자 상황에서 2로 나누어 떨어질 때, 3으로 나누어 떨어질 때, 6으로 나누어질때, 그렇지 않을때 이렇게 케이스 분류를 하다가 머리를 엄청 싸맸습니다. 
---
```java
private static int dp(int k) {
if (k==0||k==1||dp[k] != 0) return dp[k];
else {
if (k%6 == 0) {
dp[k] = Math.min(Math.min(dp(k/3), dp(k/2)), dp(k-1)) + 1;
} else if (k%3 ==0) {
dp[k] = Math.min(dp(k/3),dp(k-1)) +1;
} else if (k%2 ==0) {
dp[k] = Math.min(dp(k/2),dp(k-1)) +1;
} else {
dp[k] = dp(k-1) + 1;
}
}
return dp[k];
}
```
- 재귀를 활요합니다.
- 종료 조건1 :  k값이 0 또는 1인 경우, 또는 dp[k]가 0이 아닌 모든 경우(이미 계산된 경우) 기본값인을 그대로 반환합니다.
- 그렇지 않은 모든 경우에 대하여
6의 배수일 경우, 3으로 나눈 경우, 2로 나눈 경우 1로 나눈 …
=> BOJ_1463 풀이

src/밀러/BOJ_1463.py
안녕하세요 BOJ 1463 번 문제풀이를 들고 온 Miller 입니다.
일단 제가 이 문제를 고른 이유는 DP(동적계획법) 을 한 번도 풀어본 적이 없었기 때문입니다.
문제 출제를 위해 알고리즘 분류를 이미 알고 고른 문제여서, 상향식/하향식 접근법 중 하향식으로 접근하고자 했습니다.
```python
dp = [0 for _ in range(N + 1)]
dp[1] = 0
def solution(n: int) -> int:
if n == 1 or dp[n]:
return dp[n]
if n % 3 == 0:
dp[n] = solution(n // 3) + 1
return dp[n]
if n % 2 == 0:
dp[n] = min(solution(n // 2), solution(n - 1)) + 1
return dp[n]
dp[n] = solution(n - 1) + 1
return dp[n]
```
먼저 3으로 나눌 수 있는 경우 나누고, 그렇지 않은 경우 2로 나누기와 1 빼기 중 작은 값을 반환하는 값을 택하려고 했습니다.
근데 이 방법으로 채점을 해보니 60% 대에서 '틀렸습니다' 가 뜨더라구요...?
이해가 안가서 고쳐보다가 도저히 로지컬 에러를 못찾을 것 같아, 결국 상향식 접근법으로 풀었습니다.
```python
def solution(n: int) -> int:
dp: List[int] = [sys.maxsize for _ in range(N + 1)]
dp[1] = 0
for i in range(2, n + 1):
dp[i] = dp[i - 1] + 1
if i % 2 == 0 and …
```
=> [Miller] BOJ(1463): 1로 만들기 - 문제풀이

src/짱민/1463.py
DP를 안쓰면 못푸는 문제네요~~
시간복잡도 계산은 사실 잘 못하지만,,, 파이썬3 기준으로 1.5초고 N의 범위가 백만이니 O(NlogN) 에서 O(N) 정도의 방법을 쓰면 될 것 같네요. 제 방법은 야매식 NlogN 인것 같습니다
전에 풀어봤던 문제라 DP인건 알고 있었으나 풀고나서 전의 제 코드를 보니 거의 다르게 풀었더군요
배열하나를 선언해놓고 dfs로 최단거리를 구하는 것처럼 풀었습니다.
파이썬은 인터프리터 언어라서 아마 인덱싱 과정에서 pointer%3 이나 pointer//3 같은 코드가 반복돼서 연산량이 좀 늘었을 수도 있습니다. 자바는 상관 없을 것 같은데 이부분 최적화 하면 소요시간이 더 줄 것같습니다.
3가지 경우를 모두 생각해서 각각 if문으로 분기를 나눴어야 하는데 무의식적으로 if -elif - elif로 구현해서 1차 난관
pointer//3 같은 코드를 박아서 넣다보니 오타가 발생해서로 2차 난관
결론 : 문제풀이에도 클린 코드가 필요하다....
=> [zzangmin] BOJ(1463): 1로 만들기

src/산토리/등굣길.py
안녕하세요. 산토리입니다.
화요일 문제 풀이 업로드합니다~
각 칸에 최단거리로 이동하는 경우의 수를 dp 배열에 담아 풀이했습니다.
최단거리로 이동하는 경우의 수 문제 풀듯이, dp[r][c] = dp[r-1][c] + dp[r][c-1] 을 통해 경우의 수를 계산해나갑니다.
이 때, 물 웅덩이의 처리는 해당 칸의 경우의 수를 0으로 만드는 것입니다.
물 웅덩이를 지나갈 수 없기 때문에 도달할 수 있는 경우의 수가 0이기 때문입니다.
그렇게 처리하고 진행하여 맨 마지막 칸의 dp값을 반환하면 됩니다.
1. 처음에는 전체 경우의 수에서 웅덩이를 지나는 경우의 수를 빼려고 했는데, 웅덩이가 여러 개일 수 있기 때문에 모든 웅덩이를 고려해야 했다. 
2. 첫 행과 첫 열은 무조건 1일 거라 생각했는데, 웅덩이가 등장한 이후의 칸들은 최단거리 경로에서 제외되기 때문에 경우의 수를 0으로 생각한다.
MxN 격자를 모두 순회하므로 O(MN)입니다.
=> [산토리] 프로그래머스(42898): 등굣길 - 문제풀이

src/땃쥐/Programmers_42898.java
안녕하세요... 어려운 문제를 주셨군요...
풀리퀘 올립니다.
---
m,n 이중 for문 돌면서 처리하므로 시간 복잡도는 O(mn)일 것으로 추정됩니다.
---
무작정 다 더해서 마지막 값만 나머지 처리를 했는데, 이 부분에서 효율성 테스트가 빨간불이 뜨더라구요.
그래서, 각 값을 합치는 과정에서부터 나머지 처리를 했습니다.
(a+b....+z)%m = (a%m + b%m+ ... + z%m)%m 인 것을 이용했는데 왜 이렇게 하면 효율성이 좋아지는지 아직 잘 모르겠습니다.
```java
int[][] routeCounter = new int[n+1][m+1]; // 각 인덱스는 그 지점에 올 수 있는 가짓수로 취급
for (int[] puddle : puddles) { // 웅덩이는 일단 -1로 체킹
routeCounter[puddle[1]][puddle[0]] = -1;
}
routeCounter[1][0] = 1; // 1,1의 왼쪽값을 1로 가정
for (int i=1; i<=n; i++) {
for (int j=1; j<=m; j++) {
if (routeCounter[i][j] == -1) {
routeCounter[i][j] = 0; // 웅덩이가 있는 곳에 올 수 있는 경우의 수는 0이다.
} else {
routeCounter[i][j] = (routeCounter[i][j-1] + routeCounter[i-1][j])%1_000_000_007;
// 위의 좌표에 도달할 수 있는 경우의 수 + 왼쪽의 좌표에 도달할 수 있는 경우의 수
}
}
}
```
- 이차원 배열을 정의합니다.
- …
=> [땃쥐] 프로그래머스 (42898) : 등굣길 - 문제풀이

src/산토리/종이의 개수.py
안녕하세요. 산토리입니다.
목요일 문제 풀이 업로드합니다~
주어진 종이를 탐색하다가 조건을 만족하지 않는 경우 작은 종이로 쪼개서 다시 탐색합니다. 재귀나 스택을 사용해 조건이 맞지 않을 때마다 연산을 추가해주는 식으로 접근해보려고 했습니다.
스택에 탐색할 범위를 저장해두었다가 하나씩 꺼내서 해당범위를 탐색하기 시작합니다.
처음에는 전체 범위를 넣고, 만족하지 않을 때마다 9조각으로 나눈 범위를 stack에 넣어줍니다
처음에 stack에 탐색할 board의 일부분을 모두 저장했더니 메모리 초과가 발생했습니다. 그래서 그냥 탐색할 범위만 기록해두고 원본 board의 index 접근을 통해 조사하는 것으로 개선했습니다.
추가로 size가 1칸인 경우는 무조건 조건을 만족하므로 stack에 담지않고 미리 반영하고 건너뜁니다.
최악의 경우는 전체가 크기 1짜리 종이로 찢어지는 경우일 것 같습니다.
그럴 때 결국 스택 계산을 1+9+81+... 번 하게 되는데 총 횟수는 (9^(k+1)-1)/8이 됩니다.
9^(k+1) = 3^k = N의 제곱 꼴이므로, O(N^2)인 것 같습니다.
=> [산토리] BOJ(1780): 종이의 개수 - 문제풀이

src/밀러/BOJ_1780.py, src/밀러/BOJ_2630.py
안녕하세요, BOJ 1780 문제 풀이를 들고온 Miller 입니다
재귀로 풀어야할 것 같은데, 오랫동안 생각해봐도 어떻게 풀어야할지 전혀 몰라서 힌트를 보고 분할 정복으로 풀어야겠다고 생각했습니다. 그런데도 풀이가 안 떠올라서 땃쥐가 참고 문제로 주신 2630 번 문제부터 풀었습니다.
그런데 제가 예전에 풀었던 문제더라구요..? 하지만 그렇다고 풀이가 생각나지는 않았는데,
분할정복을 조금 공부해보고자 병합 정렬 (merge sort) 을 보고 조금 아이디어를 얻었습니다.
분할정복을 할 때 분할 시에 배열의 인덱스를 넘기는 게 아니라 배열 전체를 분할해 넘기는데,
이 문제에서도 마찬가지로 배열 전체를 분할해 넘기고자 했습니다.
하지만 최적의 풀이는 아닌 것 같습니다. 간신히 제한된 시간을 통과한 것 같아요.
재귀 문제를 다룰 때마다 시간 복잡도를 계산하기 어렵네요. 뭘까요..?
=> [Miller] BOJ (1780) : 종이의 개수 - 문제 풀이

src/아더/BOJ_1780_종이의개수.java
이번 문제는 대충 이런식으로 풀어야겠다고 생각은 들었지만 풀이방법이 떠오르지 않아 힌트를 참고했습니다.
분할정복 및 재귀 문제라는 것을 깨닫고 좋은 주제라고 생각했습니다.
최근에 정형화된 코테문제만 풀다보니 요런 주제를 많이 접하지못해 헤맸는데 좋은 기회였습니다!
그리고 땃쥐 PR 메시지를 보았는데 항상 순위에서 1위를 차지하시는 것 같아서 한 번 설명들어보고 싶어요!
정확한 시간복잡도 계산이 어렵네요... 일단 `isAllSameNumber`에서 계속 배열을 순회하고 `divideConquer`에서도 배열을 순회해서 꽤 나올거 같긴합니다....
1. 분할정복이라는 키워드를 통해 3분의 1씩 작아질 수 있게 변수를 구성했습니다.
2. 현재 모든 요소가 같은 지를 판단하는 메소드는 2차원 배열을 전부 순회중입니다.(이 부분을 개선할 수 있는지 고민되네요)
3. 정답은 3의 길이를 가진 배열에 차례차례 넣고 출력합니다.(-1, 0, 1의 값들을 가지므로 +1을 해주어 인덱스예외를 방지합니다)
1. 3분의 1씩 줄어든다는 개념은 이해했으나 코드로 옮기는 것에 실패했습니다.
4. 힌트와 다른 사람 풀이를 참고해서 문제를 풀이했습니다  ㅠㅠ
=> [Ader] BOJ (1780) : 종이의 개수 - 문제 풀이

src/제이/week3/BOJ_1780.java
안녕하세요 Jay 입니다.
먼저 늦게 제출하는점 죄송하다는 말씀 드리고, 기다려주신 땃선생님과 다른 선생님들께 감사드립니다 ㅠㅠ
이번 문제는 고민을 해봐도 도저히 감이 안와서, 알고리즘 분류만 참고하였습니다.
재귀 문제는 시간 복잡도 계산이 어려운것 같습니다...
그런데 결국 전체 종이를 다 확인해야하니, O(N^2) 인것 같기도 한데.. 확신은 들지 않네요.
`분할 정복` 과 `재귀` 라는 키워드를 통해 한 페이지씩 확인 후 재귀 호출을 통해 더 작은 페이지를 확인하는 방식으로 접근하였습니다.
재귀호출을 할때, 기존 크기의 1/3 만큼만 탐색하도록 구현하였습니다.
키워드를 얻기 전에는 BFS 로 풀어야 할까 아주 잠깐 고민했었는데,
BFS 로 풀이할 수 있는 문제가 아닌것 같아 알고리즘 분류만 확인하였고,
키워드를 얻고 나서는 크게 삽질 과정은 없었던 것 같습니다..!
=> [Jay] BOJ (1780) : 종이의 개수 - 문제 풀이

src/산토리/계단 오르기.py, src/산토리/종이의 개수.py
안녕하세요. 산토리입니다.
토요일 문제 풀이 업로드합니다~
예전에 풀어보았던 문제라 쉽게 접근 과정이 떠올랐던 것 같습니다.
N번째 계단에 도착할 때 가능한 경우의 수는 2가지 입니다.
- 1칸을 이동해서 N번째 칸에 도착한 경우
- 2칸을 이동해서 N번째 칸에 도착한 경우
즉, dp 배열에서도 각 칸마다 2가지 경우를 모두 고려해줘야 합니다.
dp[n][0]을 1칸 이동한 경우, dp[n][1]을 2칸 이동한 경우로 생각했습니다.
1. 1칸 이동한 경우
1칸 이동한 경우에는 n-1번째 칸을 1칸을 움직여 도착한 경우는 불가능합니다. 연달아 3칸을 밟을 수 없기 때문입니다. 
그래서 max(n-1번째 칸을 2칸 움직여 도착한 경우, n-2번째 칸을 1칸이나 2칸 움직여 도착한 경우)
+ n번째 칸의 점수로 갱신합니다.
2. 2칸 이동한 경우
2칸 이동한 경우는 n-2번째 칸에 어떻게 몇칸을 이동해 도착했는지 상관 없으므로 단순하게 계산이 가능합니다.
max(n-2번째 칸에 1칸이나 2칸 움직여 도착한 경우) + n번째 칸의 점수로 갱신합니다.
마지막에는 N번째 칸 중 1칸 움직인 것과 2칸 움직여 도착한 경우 중 큰 값을 반환합니다. 
처음에는 dp를 2차원으로 관리할 생각을 못했는데 하다보니 생각이 났습니다.
결국 계단의 수 N만큼만 계산하므로 O(N)입니다.
=> [산토리] BOJ(2579): 계단 오르기 - 문제풀이

src/밀러/BOJ_2579.py
늦게 올려서 죄송합니다 ㅠㅠ 2579번 풀이를 가져온 Miller 입니다.
계단을 오르는 것을 보고 피보나치 수열처럼 점화식으로 풀어야겠다고 생각했습니다.
그리고 어떤 계단 위치에 있을 때, 해당 위치로 반드시 와야하는 경우를 따져보았습니다.
두 칸 아래에서 이동했을 경우, 두 칸 아래보다 아래에서는 어떤 일이 벌어지든 상관없습니다.
따라서 아래와 같이 점화식을 세울 수 있었습니다.
```python
answer[m] = stairs[m] + max(recursion(m - 2), stairs[m - 1] + recursion(m - 3))
```
인덱스가 헷갈릴 것 같아, 입력을 받을 때 맨 앞에 시작점의 점수를 0 으로 추가했습니다.
이렇게 하면 n 번째 계단 = stairs[n] 으로 되어 생각이 간편해졌습니다.
재귀만으로 풀고 문제를 제출했더니 바로 시간초과가 떴습니다.
배열에 저장하고 풀었더니 통과되었습니다. 메모이제이션 최고!
=> [Miller] BOJ(2579): 계단 오르기 - 문제풀이

src/땃쥐/BOJ_2579.java
문제를 풀려고 몇 번 시도해봤지만 이해하기 힘들어서 답을 좀 봤습니다. ㅜㅜ;
일단 계단을 몇 번 그려보고 가지케이스로 테스트 케이스를 몇 번 그려보면서 '룰'을 이해하려는 시도를 해봤습니다. 도저히 제가 가진 지식으로 처리할 수 없어서 힌트를 봤습니다. 
DP라는 것이 이전 단계까지의 과정을 저장해두고 다시 꺼내씀으로서 한번 계산하는 것을 다시 계산하지 않는 기법이라는것을 배웠지만, 실제 문제 풀때는 바로 적용되지않네요. 그래서 또 답을 봤습니다
---
N번째 계단에 도달하는 경우는 결국 두가지로 이분됩니다.
1. 한칸 아래에서 올라오거나.
2. 두칸 아래에서 바로 올라오거나.
두칸 아래에서 올라오는 경우에는, 연속해서 세 계단이 와선 안 된다는 제약 하에서 자유롭습니다. 그 아래에서 어떻게 오든, 두칸 아래에서 오는 경우는 조건에서 문제가 되지 않습니다.
하지만, 한칸 아래에서 올라오는 경우에는, 두칸 아래-한칸아래와 같은 상황에서 올라왔을 경우에는 규칙을 어기는 접근이 되버립니다. 한칸 아래에서 올라올 경우에는 세칸 아래에서 건너 뛰어 한칸 아래에 오고, 한칸 아래에서 다음 칸으로 와야할 수밖에 없습니다.
```java
private static int calMaxScore(int k) {
if (maxScores[k] == null) {
maxScores[k] = Math.max(calMaxScore(k - 3) + stair[k - 1], calMaxScore(k - 2)) + stair[k];
}
return maxScores[k];
}
```
k번째 칸에 오기까지의 조건을 재귀함수를 통해 …
=> [땃쥐] BOJ(2579): 계단 오르기 - 문제풀이

src/제이/week3/BOJ_1780.java, src/제이/week3/BOJ_2579.java
DP 를 이용하여 풀이하였기 때문에, 시간 복잡도는 O(n) 입니다.
여러 삽질 끝에 DP 로 문제풀이를 하려고 했고, 각 번째를 한 번만 구하려면 결국 식이 필요했습니다.
재귀로 계산하면 한 계단을 여러번 계산해서 비교해야 하기 때문에, 시간복잡도를 줄일 수 없어서 시간 초과가 발생합니다.
고민하던 중 예전에 밀러의 접근 방식 중 점화식을 정의하고 문제를 풀었던 것을 인상깊게 본 기억이 났습니다.
그래서 이번 문제를 잘 살펴보다 보니 점화식을 정의할 수 있을 것 같아서 시도해봤습니다.
1. `n 번째의 합` = `n-2 번째 까지의 합` + `n 번째 계단 점수`
2. `n 번째의 합` = `n-3 번째 까지의 합` + `n-1 번째 계단 점수` + `n 번째 계단 점수`
1과 2 중 큰 것을 `n 번째의 합`으로 지정합니다.
```java
for (int i = 3; i < size; i++) {
int calc1 = maxScores[i-2] + scores[i];
int calc2 = maxScores[i-3] + scores[i-1] + scores[i];
maxScores[i] = Math.max(calc1, calc2);
}
```
처음에 재귀를 통한 계산으로 제일 마지막 계단의 최대값을 구하려 했습니다.
이 방법으로 계산하면 정답은 나올 것 같았지만, 시간복잡도를 줄일 수 없는 방법이었습니다,
그래서 이번 문제도 알고리즘 분류를 참고하여 문제를 풀이했습니다..ㅠㅠ
(언제쯤 힌트 없이 풀 수 있을까요..)
=> [Jay] BOJ (2579) : 계단 오르기 - 문제 풀이

src/산토리/연산자 끼워넣기.py
안녕하세요. 산토리입니다.
화요일 문제 풀이 업로드합니다~
그리디적으로 수식의 최소, 최대를 결정하기에는 생각할 것이 너무 많아보여서 모든 경우의 수를 다 뒤져보는 방법을 선택했습니다. 
DFS와 같이 수행해보면 좋을 것 같아서 재귀를 통해 풀었습니다.
각 연산자의 순서에 따라서 가지치기를 해가면서 재귀로 계산하면 모든 경우의 수가 저장될 것입니다. 
`calculate` 함수가 호출되면 연산자 개수가 저장된 배열을 순회합니다. 
남은 연산자가 있으면 해당 연산자의 개수를 하나 깎고 계산한 결과와 남은 연산자 개수를 담아 재귀호출합니다. 이 때 재귀호출 종료조건은 숫자의 개수가 주어진 숫자의 개수와 같아질 때입니다.
모든 숫자를 계산했으면 결과 배열에 저장하고 return합니다.  
삽질 과정은 아니고 이렇게 연산자의 경우의 수를 세면 같은 것이 있는 순열이라서 중복되는 경우도 셀 것이라고 생각했습니다. 
그래서 시간 초과가 나지 않을까했는데 어차피 for문으로 가지치기를 하기 때문에 각 경우를 한번만 순회한다는 것을 알게 되었습니다. 
연산자를 배치하는 경우의 수가 대략 (N-1)! / ((N/4)!^4) 의 경우의 수를 가지는데 N이 커질수록 O(N!)에 접근할 것 같습니다.
문제에서는 최대 N이 11밖에 되지 않아서 만 여번정도만 계산하면 돼서 문제가 없는 것 같습니다.
=> [산토리] BOJ(14888): 연산자 끼워넣기 - 문제풀이

src/밀러/BOJ_14888.py
안녕하세요, BOJ 14888번 풀이를 들고 온 Miller 입니다 🤿
PR 을 늦게 올려서 죄송합니다 ㅠㅠ
이 문제를 봤을 때 순열/조합 문제이므로 DFS 와 백트래킹을 이용하고자 했습니다.
이 문제의 각 연산자인 `+`, `-`, `*`, `//` 는 아래와 같은 그래프 구조를 가지고 있습니다. 
그리고 문제의 에시에 나온 것처럼 각 `+`, `-`, `*`, `//` 가 각각 2, 1, 1, 1 개로 주어진다면,
`rest` 라는 배열을 [2, 1, 1, 1] 로 구성하고, 해당 노드에 방문할 경우 해당 `rest` 에서 해당 인덱스에서 -1 합니다.
그리고 방문한 노드는 `route` 배열에 방문한 노드를 추가합니다.
예를 들면 맨 처음 `+` 를 방문하면 `rest` 는 [1, 1, 1, 1], `route` 는 [0]
다시 `+` 를 방문하면 `rest` 는 [0, 1, 1, 1], `route` 는 [0, 0] 이 됩니다.
이런식으로 각 노드를 방문하다가 `route` 의 길이가 5가 되면,
전역 변수인 `routes` 에 해당 `route` 를 복사해 추가합니다.
결과적으로 `routes` 는 같은 것을 포함하는 순열의 모든 경우의 수로 구성된 배열로, 위의 예에서는 총 60개의 원소를 가집니다.
`dfs()` 함수로 어떤 노드에 접근한 뒤에 해당 노드에 연결된 다른 노드를 모두 순회한 뒤에는
`rest` 배열에서 해당 노드의 인덱스에서 +1 하고, `route` 배열에서 가장 최근에 추가된 노드를 `pop()` 합니다.
즉, 현재 노드에서 상위 노드로 다시 back 할 때, 원상복구 시켜놓고 …
=> [Miller] BOJ(14888) : 연산자 끼워넣기 - 문제 풀이

src/땃쥐/BOJ_14888_1.java, src/땃쥐/BOJ_14888_2.java
안녕하세요. 풀 리퀘스트 드립니다. 문제 제출 늦게해서 죄송합니다...
- 일단 내용 자체를 이해하지 못 해서 힌트를 봤습니다. 힌트를 봐도 백트래킹이 몰라서, 더 [간단한 난이도의 문제](https://www.acmicpc.net/problem/15649)를 잠시 해답을 참고하고 풀어봤습니다. 
- 힌트를 보면서 풀었음에도 깊이에서 뭔가 연산 결과가 어긋나거나, 하는 경우가 계속 발생해서 2-3시간 이상을 날린 것 같습니다.
```java
public static void bt(int currentValue, int depth) {
if (depth == N - 1) {
max = Math.max(max, currentValue);
min = Math.min(min, currentValue);
return;
}
for (int i = 0; i < N - 1; i++) { // 0,1,2,3,...,N-2
if (!visited[i]) {
visited[i] = true;
bt(functions.get(i).applyAsInt(currentValue, numbers[depth + 1]), depth + 1);
visited[i] = false;
}
}
}
```
- ArrayList에 N-1개의 IntBinaryOperator를 순서대로 넣었습니다.(+,-,*,/)
- 각 인덱스에 접근했는지 여부를 boolean 배열에 기록하고 백트래킹에 사용합니다.
- 최대 깊이보다 더 깊은 깊이에 도달했을 때 최대 최소를 갱신합니다.
- 이 방식은 420ms정도 시간 걸립니다.
---
```java
public …
```
=> [땃] BOJ(14888) : 연산자 끼워넣기 - 문제 풀이

src/제이/week4/BOJ_16918.java
생각했던 풀이 방식은 O(N^3) 의 시간복잡도를 가집니다.
문제의 입력에 따라 최대 `8,000,000` 번의 좌표 확인을 하는데, 폭탄이 터질 경우 각 좌표의 상하 좌우를 확인합니다.
그래서 이에 `4`를 곱하여 `32,000,000` 번의 연산을 하게될 수 있습니다.
하지만 시간 제한이 2초이기 때문에, 여유가 있다고 생각했습니다.
맵 전체를 `int[][]` 로 선언하고, 폭탄이 설치될 경우 해당 위치에는 폭탄이 터지는 시간인 `3`으로 초기화 해주었습니다.
그리고 `제한시간`까지, `설치` 또는 `폭발`을 반복해서 수행하는 방식으로 해답을 구했습니다.
답을 구하는데는 삽질이 없었습니다.
대신 풀이를 제출해보니, 시간 복잡도가 높게 나와서 줄이려고 시도해보며 삽질을 했었습니다.
그래도 삽질을 하며 `792ms` -> `168ms` 로 감소시키는데 성공하여 보람이 있었고,
코드에 병목이 되는 부분을 찾는 연습이 되어, 앞으로는 처음부터 병목이 되는 부분을 생각하며 코딩할 수 있을 것 같습니다.
`792ms`-> `368ms` = `424ms 감소`
생각없이 한줄씩 System.out.print 를 해줬었는데, 이게 가장 큰 병목이었던 것 같습니다..
`368ms`-> `344ms` = `24ms 감소`
입력값을 정규식으로 필터링하여 입력받는 `Scanner` 대신, `BufferedReader` 로 대체하였습니다.
아주 큰 시간 감소는 아니었지만, 큰 입력값을 정규식 필터링을 하며 발생하는 오버헤드가 시간을 조금 더 소모했던 것 같습니다.
`344ms` -> `332ms` = `12ms 감소` …
=> [Jay] BOJ (16918) : 봄버맨- 문제 풀이

src/산토리/최소비용 구하기.py
안녕하세요~ 산토리입니다.
화요일 문제 풀이 올립니다!
전형적인 다익스트라 알고리즘 문제로 보여 바로 다익스트라 구현에 집중했습니다.
오랜만에 써보는 알고리즘이라 구현하는 방향을 까먹어 삽질을 좀 했던 것 같습니다.
상길북의 psuedo code를 참고하여 우선순위 큐를 이용한 다익스트라 알고리즘으로 풀었습니다.  
1. 단방향 그래프 작성: 파이썬의 defaultdict 자료구조(HashMap과 유사)를 사용하여 작성하였습니다.
```python
graph = defaultdict(list)
for _ in range(M):
u, v, w = list(map(int, input().split()))
graph[u].append((v, w))
```
2. 최소 비용을 저장할 defaultdict와 우선순위 큐(최소 힙으로 구현) 생성한 다음 우선순위 큐에 시작점 push
```python
cost = defaultdict(int)
heap = []
heapq.heappush(heap, (0, dep))
```
3. heap에 담긴 node를 순회하며 최소비용 업데이트가 되지 않은 node이면 업데이트
```python
while heap:
cur_cost, cur_node = heapq.heappop(heap)
if cur_node not in cost:
cost[cur_node] = cur_cost
for adj_node, adj_cost in graph[cur_node]:
next_cost = cur_cost + adj_cost
heapq.heappush(heap, (next_cost, …
```
=> [산토리] BOJ(1916): 최소비용 구하기 - 문제풀이

src/밀러/BOJ_1916.py
안녕하세요, 최소비용 구하기 문제풀이를 들고온 밀러입니다 🧵
일단 먼저 DFS 로 풀었는데 시간복잡도가 발생했습니다.
그래프에서 간선의 가중치가 주어질 때 최소비용을 구하는 문제를 다익스트라 알고리즘으로 풀어야 한다고 알고 있었는데,
이전에 리트코드에서 풀었던 문제들은 DFS 로도 풀려서 이번에는 안되더라구요.
다익스트라 알고리즘에서 우선순위 큐를 이용했고,
큐 내부에서 최소힙으로 우선순위를 조정하면서 가중치의 합이 최소인 노드만 뽑아 해결할 수 있었습니다.
덕분에 항상 대충 DFS 로 풀었던 다익스트라 알고리즘을 풀 수 있어 좋았습니다.
아 그리고 백준에서 처음으로 골드 문제를 풀었네요! 감사합니다 땃쥐!
=> [Miller] BOJ(1916): 최소비용 구하기 - 문제풀이

src/밀러/PROGRAMMERS_72413.py
안녕하세요, 프로그래머스 합승 택시 요금 문제 풀이를 들고온 밀러입니다 🏃‍♂️
이번 문제 생각하기 쉽지 않았고, 처음 생각했던 풀이가 효율성에서 시간 초과가 발생해 시간을 많이 썼습니다 ㅠ
먼저 제가 이 문제를 보고 생각한 전제는 다음과 같습니다.
> 출발지점 `s` 로부터 어떤 경유지 `m` 까지의 최소 요금을 계산하고, `m` 에서 도착지점 `a` 와 `b` 까지의 최소요금을 합해서 더하면 경유지 `m` 을 거칠 때 최소 요금이다.
그리고 위 전제로부터, 그래프 내의 모든 노드를 순회하면서 각 노드가 경유지일 때의 최소 요금을 계산하고,
그 중에서 가장 작은 값을 답으로 구하려고 했습니다.
그리고 아래와 같은 다익스트라 알고리즘을 적용한 함수를 모든 노드마다 3번씩 적용하고자 했습니다.
아래 함수를 실행하면, `start` 에서 `end` 까지 최소 요금을 구할 수 있습니다.
```python
dist: Dict[int, Dict[int]] = {}
def dijkstra(start: int, end: int):
queue = [[0, start]]
dist[start] = {}
tmp: Dict[int, int] = {}
while queue:
cost, now = heapq.heappop(queue)
if now in dist[start]:
continue
tmp[now] = cost
for dest, weight in graph[now]:
alt: int = cost + weight
heapq.heappush(queue, [alt, dest])
dist[start][end] = tmp[end] …
```
=> [Miller] PROGRAMMERS(72413): 합승 택시 요금 - 문제풀이

src/밀러/BOJ_11657.py
안녕하세요, 백준 타임머신 문제 풀이를 들고온 밀러입니다 ✍
이번 문제는 제가 출제하기도 했고, 벨만-포드 알고리즘의 학습에 초점을 맞춰 해당 알고리즘을 공부하고 문제를 풀이해 별도의 삽질이 없었습니다.
이전에 다룬 문제들에서는, 어떤 정점에서 모든 정점까지의 거리(혹은 비용)을 계산할 때 다익스트라 알고리즘을 사용했습니다.
하지만 이번 문제는 그래프에 음의 가중치를 갖는 간선이 있어 다익스트라 알고리즘을 사용할 경우, 음수인 간선의 가중치를 처리할 수 없습니다.
따라서, 음수인 값을 처리할 수 있는 벨만-포드 알고리즘으로 풀이해야합니다.
벨만-포드 알고리즘을 활용한 함수는 아래와 같습니다.
```python
def bellman_ford(start: int):
dist[start] = 0
for turn in range(N):
for edge in edges:
now, dest, cost = edge
if dist[now] != INF and dist[dest] > dist[now] + cost:
dist[dest] = dist[now] + cost
if turn == N - 1:
return False
return True
```
벨만-포드 알고리즘에서는 `V-1` 번 동안, 각 간선마다 edge relaxation 과정을 반복해야합니다. edge relaxation 에서는 출발 정점에서 간선의 종점까지 최소 비용보다 간선의 기점까지의 최소 비용 + 간선의 비용이 더 작을 경우 최소 비용을 갱신합니다.
그리고 `V - 1` 번 동안 반복한 후, 이후에도 최소 비용 갱신이 이루어지면 음의 값으로 인한 …
=> [Miller] BOJ(11657): 타임머신 - 문제풀이

src/아더/BOJ_11657_타임머신.java
이번주는 시간복잡도 특집이네요 ㅋㅋㅋㅋ
음수로 가중치가 주어지는 문제는 처음 접해봐서 `밀러`가 가이드해주신대로 `벨만포드 알고리즘`을 먼저 학습하고 문제를 풀어보았습니다. 좋은 알고리즘을 연습할 수 있게 문제를 출제해주신 `밀러` 감사합니다!
벨만포드 알고리즘의 시간복잡도는 `O(VE)`라고 하네요.
다익스트라보다는 느립니다. 하지만 `음수간선의 순환을 감지`할 수 있다는 알고리즘이므로 꼭 알아둬야겠네요.
1. 출발노드를 설정합니다. 1번 점이 출발점이니 `dist[1] = 0`으로 초기화합니다.
2. dist[] 배열의 나머지를 `Arrays.fill(dist, Integer.MAX_VALUE)`로 초기화합니다. 이 과정에서 `dist 배열은 long 타입`으로 선언되어야 합니다.
3. 아래의 과정을 정점의 갯수만큼 반복합니다.
4. 전체 간선을 확인합니다. 최단거리가 있다면 갱신합니다.
5. `N-1`번째까지 갱신을 계속한다면 음수 사이클이 있다고 판단하고 true를 리턴하도록 합니다.
1. 기존 다익스트라 풀이에서 사용하던 `우선순위 큐`를 계속 사용했는데 이것 때문에 예시 테스트케이스2에서 계속해서 무한루프가 발생했습니다.
2. 그래서 `우선순위 큐`를 빼버리고 그냥 모든 점의 모든 간선을 순회하며 계산했습니다.
=> [Ader] BOJ(11657): 타임머신 - 문제풀이

src/제이/week6/BOJ_2056.java
시간 복잡도 계산이 어렵네요,,
O(N^2) 가 걸릴 것 같습니다.
작업 문제는 위 그림 처럼 선행 작업이 완료되어야 해당 작업이 시작되며, 이 작업들은 병렬적으로 처리 가능한 문제 입니다.
문제를 풀기위해 먼저 `작업` 들에게 `번호(index)`, `소요시간(time)`, `내가 끝나기를 기다리는 작업의 번호(waitings)` 를 저장했습니다.
그리고 `작업의 선행 작업 개수(relations)`들을 저장하였는데요.
그러면 특정 작업이 끝났을 때, `waitings` 들의 `relations`를 하나씩 줄여나가며 만약 개수가 0이 된 작업이 있다면,
해당 작업을 시작 시키는 방식으로 동작하게 하게 하였습니다.
이렇게 하면 `작업의 동시성`과 `선행 작업 완료 여부를 확인`을 하며 작업들을 진행시킬 수 있습니다.
아래 핵심로직 및 주석을 첨부합니다.
```java
List<Task> startedTask = new ArrayList<>(); // 시작된 작업
List<Task> finishedTask = new ArrayList<>(); // 끝난 작업(startTask 에서 제거할 Task 들)
// 선행 관계가 없거나 완료된 Task(relations == 0) 들을 시작할 목록에 추가
addStartableTask(startedTask);
int time = 0;
while(startedTask.size() > 0) {
time++;
for (Task currTask : startedTask) {
currTask.tick(); // Task 작업 수행 (시간 -1)
// 현재 Task 끝났으면, 이 …
```
=> [Jay] BOJ(2056): 작업 - 문제풀이

src/산토리/공유기 설치.py
안녕하세요! 산토리입니다.
목요일 문제 풀이 업로드합니다~
이분 탐색으로 풀어보면 될 것 같아서 이분탐색을 했는데 정답을 기록하는 조건을 헷갈렸습니다. 집을 순회하면서 정해진 거리 이상이면 무조건 공유기를 설치하도록 했습니다. 그래서 딱 정해진 개수에 맞게만 설치된 경우만 체크하려고 하면 실제로는 만족하는 경우가 있더라도 정답 후보에서 빠지게 됩니다. 정해진 개수보다 많은 경우에는 어느 집에서 공유기 몇개를 빼더라도 여전히 가장 짧은 거리는 동일할 것이므로 많은 경우도 포함해줘야 되는 것을 깨달았습니다. 
예전에 [비슷한 문제](https://programmers.co.kr/learn/courses/30/lessons/43236)를 푼 기억이 있어서 비슷한 방식으로 풀어봤습니다.
가장 인접한 집 사이의 거리를 임의로 정해놓고 이 거리를 만족하면서 공유기를 설치할 수 있는지를 검사합니다. 이 때 거리를 이분탐색하며 탐색을 진행합니다.
집을 위치순으로 정렬해놓고, 한 집에서 다음 집까지의 거리가 현재 만족해야 하는 거리보다 짧으면, 공유기를 설치하지 않고 넘어갑니다.  
그리고 만족해야 하는 거리보다 크거나 같으면, 공유기를 설치해도 되므로 공유기를 설치하고 cnt를 1개 늘립니다.
집을 모두 순회해서 공유기 개수가 C 이상이면, 해당 거리를 만족할 수 있는 경우이므로 정답 배열에 거리를 추가하고 이분 탐색의 범위를 큰쪽으로 늘립니다.
공유기 개수가 C보다 모자라면, 거리를 더 좁혀야 한다는 말이므로 이분 탐색의 범위를 작은쪽으로 늘립니다.
이분탐색에 소요되는 시간복잡도 O(logN) * 모든 집을 순회하는 …
=> [산토리] BOJ(2110): 공유기 설치 - 문제풀이

src/땃쥐/BOJ_2056.java
문제를 늦게 제출했습니다... ㅜㅜ
---
(404ms)
- 노드의 갯수 N개를 전부 순회하고 E개의 간선들도 확인해야합니다.
- O(N+E)입니다.
---
```java
private static int N;
private static int[] costs; // 작업 비용들을 저장할 배열
private static int[] indegree; // 진입 차수(들어오는 간선의 갯수)
private static int[] results; // 각 작업을 순차적으로 작업했을 때 완료시점에서의 누적 시간
private static ArrayList<ArrayList<Integer>> nexts = new ArrayList<>();
```
- 작업의 갯수 N
- 각 작업별 비용을 정의한 costs
- `indegree[]` : 각 작업 기준 들어오는 간선의 갯수, 즉 선행작업의 갯수를 저장
- `results` : 최초 작업부터 최적시간으로 진행했을 때 해당 작업의 완료시점을 계산한 시점
- `nexts` : 각 인덱스 기준 다음에 오는 작업 번호들을 저장
```java
N = readInt();
costs = new int[N + 1];
indegree = new int[N + 1];
results = new int[N + 1];
for (int i = 0; i <= N; i++) {
nexts.add(new ArrayList<>());
}
for (int i = 1; i <= N; i++) { …
```
=> [땃쥐] BOJ(2056): 작업 - 문제풀이

src/산토리/최소 스패닝 트리.py
안녕하세요~ 산토리입니다!
처음에 각 간선의 양 끝점에 있는 정점을 다 방문처리해줘야 되는 줄 알았는데 그냥 한 정점에서 시작하여 탐색하듯이 도착점을 방문처리 해주면 되는 것이었습니다;;
가중치 합이 최소가 되려면 각 정점에서 가중치가 가장 작은 간선을 선택하면 됩니다. 각 간선을 heap으로 구성한다음 가중치가 최소인 간선을 선택해서 반영해줍니다. 선택된 간선에 해당하는 정점은 방문처리를 한다음, 모두 방문할때까지 반복합니다.
간선의 개수가 N일 때, 모든 간선에 대해 힙정렬을 수행한 것이므로 O(NlogN)입니다.
=> [산토리] BOJ(1197): 최소 스패닝 트리

src/밀러/BOJ_1197.py
문제풀이를 늦게 올려서 죄송합니다 😭
최소 스패닝 트리 문제를 크루스칼 알고리즘으로 풀이했습니다.
문제풀이 과정에서 Union-Find 알고리즘을 사용했습니다.
- `Union` : 부모가 다른 2개의 노드를 같은 부모를 가지는 하나의 트리로 합칠 때 사용 
- `Find` : 두 노드의 부모가 다른지 확인할 때 사용
비용 별로 오름차순 정렬된 간선에 대해 사이클이 존재하는지 확인하기 위해 `Find` 함수를 호출하며,
사이클이 존재하지 않는 경우에는 `Union` 함수를 호출해 최소 스패닝 트리에 간선을 추가합니다.
간선을 비용 별로 오름차순 정렬하는데 O(ElogE) 의 시간복잡도를 가집니다.
그 외에는 간선 별로 1번만 순회하기 때문에 최대 시간복잡도는 O(ElogE) 입니다.
=> [Miller] BOJ(1197): 최소 스패닝 트리 - 문제풀이

src/밀러/BOJ_1932.py
안녕하세요, 백준 정수 삼각형 문제풀이를 들고온 Miller 입니다!
늦게 제출하게 되어 죄송합니다 ㅠ
DP 를 사용하고 정수 삼각형의 크기에 따라 순회하는 횟수가 달라지므로 O(n^2) 입니다.
DP 를 활용하면서, 점화식을 더 쉽게 만들 수 있는 방법을 생각하기 위해
정수삼각형을 뒤집어서 맨 아래에서부터 맨 위로 합을 더하면서 올라가는 방법을 생각했습니다.
```python
if r == len(nums) - 1:
dp[r][c] = nums[r][c]
else:
dp[r][c] = nums[r][c] + max(dp[r + 1][c], dp[r + 1][c + 1])
```
맨 아래 줄은 정수 삼각형의 숫자값을 그대로 DP 배열에 저장하고,
그 윗줄부터는 정수 삼각형의 숫자값과 아래의 숫자 중 큰 값을 합해 DP 배열에 저장합니다.
배열의 인덱스가 하나 틀렸었는데 백준에서 맞았더라구요...?
이런 경우도 있네요 ㅋㅋ
=> [Miller] BOJ(1932): 정수 삼각형 - 문제풀이

src/아더/BOJ_14503_로봇청소기.java
이번 문제는 `DFS`로 접근했습니다.
푸쉬하고 보니까 `RobotCleaner`객체를 괜히 만들었네요;;;;
`O(V^2)`로 예상됩니다!
전체적인 `DFS` 메소드의 흐름은 다음과 같습니다
1. 벽이면 리턴, 벽이 아니라면 방문체크하고 청소구역 카운트 증가
2. 4방향 탐색
1. 현재 바라보는 방향의 왼쪽 방향 계산
2. 새로운 `row`, `column` 값 계산
3. 유효한 범위인지 판단
4. 벽인지 판단
5. 방문했었는지 판단
6. 모두 통과한다면 새로운 좌표로 dfs 시도
1. 4방향 모두  탐색했다면 한 칸 뒤로 후진해 다시 dfs  
0~3까지 차례로 북동남서 방향을 가리킵니다.
이 방향들의 왼쪽방향은 서북동남이며 이를 숫자로 나타내면 3012가 됩니다.
따라서 현재 위치를 `d`라고 한다면 `d = (d+3) % 4`라는 수식으로 왼쪽 방향을 구할 수 있습니다. 
1. 1번의 벽이 아니라는 조건에서 그냥 else를 사용했는데 조건을 확실히 해줘야 했습니다.
=> [Ader] BOJ(14503): 로봇청소기 - 문제풀이 

src/제이/week10/BOJ_14503.java
세로 = N
가로 = M
시간 복잡도  = 빈칸의 수 * 4 방향
O(NM)
- 방향 : `Direction`
- 영역 상태 : `AreaStatus`
- 로봇 청소기 : `RobotVacuum`
문제에 나오는 항목들을 객체로 만들고, 각 객체에 역할을 부여하여 구현하였습니다.
핵심이 되는 객체는 `RobotVacuum` 입니다.
- `RobotVacuum` 의 역할
- 구역 청소
- 현재 방향으로 한칸 이동
- 방향 전환
그리고 각 방향은 다음 방향을 참조하도록 하였습니다.
```java
enum Direction {
UP(new Point(0, -1)),
RIGHT(new Point(1, 0)),
DOWN(new Point(0, 1)),
LEFT(new Point(-1, 0));
static {
UP.next = LEFT;
RIGHT.next = UP;
DOWN.next = RIGHT;
LEFT.next = DOWN;
UP.back = DOWN;
RIGHT.back = LEFT;
DOWN.back = UP;
LEFT.back = RIGHT;
}
private Direction next;
private Direction back;
private final Point directionPoint;
Direction(Point directionPoint) {
this.directionPoint = directionPoint;
}
// ...
public static Direction valueOf(int value) {
switch (value) {
case 0: return UP;
case 1: return …
```
=> [Jay] BOJ(14503): 로봇 청소기 - 문제풀이

src/아더/BOJ_16926_배열돌리기.java
쉽지않네요.... 정답을 보았습니다.....
X
1. 정답 중 가장 이해할 수 있는 정답을 보고 이해하고 있습니다.
1. 처음에는 잘못된 로직으로 인해 바깥쪽 테두리만 돌렸습니다 ㅠㅠ
2. 안쪽 테두리도 돌리는 방법을 찾기 어려웠습니다.
=> [Ader] BOJ(16926): 배열돌리기1 - 문제풀이

src/밀러/BOJ_16926.py
안녕하세요, 배열 돌리기 1 문제 풀이를 들고온 Miller 입니다 😀
제가 낸 문제인만큼 주중에 계속 고민했는데, 결국 늦게 정답을 봤습니다 ㅠㅠ
아래 블로그를 참고했습니다.
<https://dkanxmstmdgml.tistory.com/731>
그리고 내부 회전 로직을 주석과 함께 정리해봤습니다.
```python
m_max = (m - 1) - cnt
n_max = (n - 1) - cnt 
tmp: int = arr[cnt][cnt]
for i in range(cnt, m_max):
arr[cnt][i] = arr[cnt][i + 1]
for i in range(cnt, n_max):
arr[i][m_max] = arr[i + 1][m_max]
for i in range(m_max, cnt, -1):
arr[n_max][i] = arr[n_max][i - 1]
for i in range(n_max, cnt, -1):
arr[i][cnt] = arr[i - 1][cnt]
arr[cnt + 1][cnt] = tmp
```
생각하기 어려운 문제였는데, 앞으로 비슷한 문제를 만났을 때 어떻게 접근해야할지
조금씩 보이는 것 같습니다.
=> [Miller] BOJ(16926): 배열 돌리기 1 - 문제풀이

src/제이/week11/BOJ_16926.java
시간 R, 가로 M, 세로 N
O(R*M*N)
위 그림처럼, 각 방향을 색으로 칠해보니 규칙성이 보였습니다.
그래서 좌표 평면에서 각 방향별 공식을 구하고 이를 이용하여 여러번 회전하도록 구현하였습니다.
```java
private static boolean isDown(double midM, int y, int x) {
return x < (int) midM && x <= y && y < N - (x + 1);
}
private static boolean isUp(double midM, int y, int x) {
return x >= midM && y >= (M - x) && y <= N - (M - x);
}
private static boolean isLeft(double midN, int y, int x) {
return y < midN && x > y && x < (M - y);
}
private static boolean isRight(double midN, int y, int x) {
return y >= midN && x >= N - (y + 1) && x < M - (N - y);
}
```
공식을 구하기까지 너무 삽질을 많이 했습니다.
엣지 케이스를 모두 만족하는 수식을 구하기 위해 여러번 수식을 고치면서 삽질을 했습니다.
=> [Jay] BOJ(16926): 배열 돌리기 - 문제풀이

src/아더/Pro_86052_빛의경로사이클.java
샤워하면서 1차 영감을 받고 밀러선생님의 코드를 보고 2차 영감을 받아 결국 해결했습니다.
1. `O(NM)`일 것 같습니다.
1. 모든 점에 대해 4가지 방향으로 시작방향을 설정하고 탐색을 합니다.
2. `visited[][][]` 배열을 두고 사이클이 생긴다면 카운트를 리턴했습니다.
1. 각 점에서 시작할 수 있는 방향을 2가지로 제한해서 생각한 점이 첫 번째 삽질입니다.
=> [Ader] PROGRAMMERS(86052): 빛의 경로 사이클 - 문제풀이 추가

src/땃쥐/Programmers86052.java
- 요구사항 분석도 지옥
- 답을 읽어도 이해하는 것도 지옥
```java
private int light(String[] grid, int row, int column, int d) {
int count = 0;
while (true) {
if (isVisited[row][column][d]) { // 해당 방향으로 빛이 사출된 이력이 있는 경우 계산하지 않는다.
break;
}
count++; // 거리 1 증가
isVisited[row][column][d] = true; // 방문 처리
if (grid[row].charAt(column) == 'L') { // 화살표를 반시계로 회전해야함. d를 -1만큼 움직여야함.
d = (d == 0) ? 3 : d - 1; // 반시계방향 (좌회전)
} else if (grid[row].charAt(column) == 'R') { // 화살표를 시계방향으로 회전해야함. d를 +1만큼 움직여야함.
d = (d == 3) ? 0 : d + 1; // 시계방향 (우회전)
}
row = (row + DIRECTION_Y[d] + HEIGHT) % HEIGHT; // 방향을 더했을 때 음이 될 수 있어서 최대 높이/너비 값을 한번 더하고 나머지 처리 해야함
column = (column + DIRECTION_X[d] + WIDTH) % WIDTH;
}
return count;
}
```
- 빛의 사출 이력을 삼차원 배열에 저장하는 특이한 구조였습니다.
- 방향을 따라 쭉 진행하면서 이미 방문했던 이력이 있는 곳으로 돌아오면 사이클 길이 계산이 끝납니다.
- 좌회전, 우회전 …
=> [땃쥐] PROGRAMMERS(86052): 빛의 경로 사이클 - 문제풀이 추가
